'use client';
import { useEffect, useState } from 'react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, getCompanyId } from '@/lib/api';

type Account={id:string;code:string;name:string};
type Row={id:string;baseDebit:string;baseCredit:string;description?:string|null;account:{code:string;name:string};journal:{journalNumber:string;transactionDate:string;sourceType:string}};
export default function Page(){return <ErpShell><Body/></ErpShell>}
function Body(){const {locale}=useLocale();const ar=locale==='ar';const companyId=getCompanyId();const [accounts,setAccounts]=useState<Account[]>([]),[accountId,setAccountId]=useState(''),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState('');const load=(id=accountId)=>apiGet<Row[]>(`/erp/account-activity/${companyId}${id?`?accountId=${id}`:''}`).then(setRows).catch(e=>setError(e instanceof Error?e.message:String(e)));useEffect(()=>{apiGet<Account[]>(`/erp/accounts/${companyId}`).then(setAccounts);load('')},[companyId]);return <><div className="heading"><div><h1>{ar?'حركة الحساب':'Account Activity'}</h1><p>{ar?'تفاصيل القيود المرحلة حسب الحساب':'Posted journal activity by account'}</p></div><button className="ghost" onClick={()=>window.print()}>{ar?'طباعة':'Print'}</button></div><section className="card"><div className="moduleToolbar"><select value={accountId} onChange={e=>{setAccountId(e.target.value);load(e.target.value)}}><option value="">{ar?'كل الحسابات':'All accounts'}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></div>{error&&<div className="formMessage">{error}</div>}<div className="tableWrap"><table><thead><tr><th>{ar?'التاريخ':'Date'}</th><th>{ar?'القيد':'Journal'}</th><th>{ar?'الحساب':'Account'}</th><th>{ar?'البيان':'Description'}</th><th>{ar?'مدين':'Debit'}</th><th>{ar?'دائن':'Credit'}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.journal.transactionDate.slice(0,10)}</td><td>{r.journal.journalNumber}</td><td>{r.account.code} — {r.account.name}</td><td>{r.description??r.journal.sourceType}</td><td>{r.baseDebit}</td><td>{r.baseCredit}</td></tr>)}</tbody></table></div></section></>}
