'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Languages, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { login } from '@/lib/api';

export default function Login(){
  const [ar,setAr]=useState(true);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const router=useRouter();
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await login(email,password);router.replace('/');router.refresh()}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}};
  return <main className="loginPage" dir={ar?'rtl':'ltr'}><section className="loginHero"><div className="heroBrand"><span className="brandMark">▥</span><b>{ar?'نظام المحاسبة':'Accounting System'}</b></div><div><h1>{ar?'محاسبتك أسهل لمستقبل أكثر نجاحاً':'Accounting Made Simple for a More Successful Future'}</h1><p>{ar?'نظام محاسبي متكامل للشركات والمتاجر، إدارة مالية ذكية في مكان واحد.':'An integrated accounting system for businesses and stores. Smart financial management in one place.'}</p></div><div className="heroTrust"><span><ShieldCheck/> {ar?'آمن وموثوق':'Secure'}</span><span>{ar?'تقارير دقيقة':'Accurate Reports'}</span></div></section><section className="loginPanel"><button className="langFloat" onClick={()=>setAr(!ar)}><Languages size={17}/>{ar?'EN':'AR'}</button><div className="loginLogo"><span className="brandMark">▥</span><h2>{ar?'نظام المحاسبة':'Accounting System'}</h2><p>{ar?'سجل دخولك للمتابعة':'Sign in to continue'}</p></div><form onSubmit={submit}><label>{ar?'البريد الإلكتروني':'Email Address'}<div className="field"><Mail size={17}/><input required autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={ar?'name@company.com':'name@company.com'}/></div></label><label>{ar?'كلمة المرور':'Password'}<div className="field"><LockKeyhole size={17}/><input required autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></div></label><div className="remember"><label><input type="checkbox"/> {ar?'تذكرني':'Remember me'}</label></div>{error&&<div className="formMessage">{ar?'تعذر تسجيل الدخول. تحقق من البيانات.':error}</div>}<button className="primary loginButton" type="submit" disabled={busy}>{busy?(ar?'جاري تسجيل الدخول...':'Signing in...'):(ar?'تسجيل الدخول':'Sign in')}</button></form></section></main>}
