'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, BarChart3, Boxes, Building2, Calculator, CheckCircle2, FileText, Languages, Landmark, LockKeyhole, Mail, Phone, ReceiptText, ShieldCheck, ShoppingCart, Wallet } from 'lucide-react';
import { login } from '@/lib/api';
import baseStyles from './login.module.css';
import marketing from './marketing.module.css';
import { PlatformLinks } from '@/components/platform-links';
const styles={...baseStyles,...marketing};

export default function Login() {
  const [ar,setAr]=useState(true), [email,setEmail]=useState(''), [password,setPassword]=useState(''), [busy,setBusy]=useState(false), [error,setError]=useState('');
  const router=useRouter();
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{await login(email,password);router.replace('/');router.refresh()}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}};
  const Arrow=ar?ArrowLeft:ArrowRight;
  const modules=[
    [ShoppingCart,ar?'المبيعات والفواتير':'Sales & invoicing',ar?'إدارة دورة البيع والفواتير ومرتجعات العملاء.':'Manage sales, invoices and customer returns.'],
    [ReceiptText,ar?'المشتريات والموردون':'Purchases & suppliers',ar?'فواتير الشراء، الموردون، المدفوعات والمرتجعات.':'Purchase bills, suppliers, payments and returns.'],
    [Boxes,ar?'المخزون والمستودعات':'Inventory & warehouses',ar?'متابعة المنتجات وحركة المخزون وتكلفة FIFO حسب المستودع.':'Track products, warehouse movement and FIFO costing.'],
    [Landmark,ar?'البنوك والتسويات':'Banking & reconciliation',ar?'حسابات بنكية واستيراد كشوف CSV ودورة مطابقة وتسوية.':'Bank accounts, CSV statement import, matching and reconciliation.'],
    [BarChart3,ar?'التقارير المالية':'Financial reports',ar?'ميزان مراجعة، دخل، مركز مالي، أعمار ذمم وتقييم مخزون.':'Trial balance, income statement, balance sheet, aging and inventory valuation.'],
    [ShieldCheck,ar?'الصلاحيات والمراجعة':'Roles & audit',ar?'صلاحيات حسب الدور وسجل مراجعة للعمليات الحساسة.':'Role-based access and an audit trail for sensitive operations.']
  ] as const;
  return <main className={`${styles.page} ${styles.pageFix}`} dir={ar?'rtl':'ltr'} lang={ar?'ar':'en'}>
    <div className={styles.backdrop} aria-hidden="true"><i/><i/><i/></div>
    <header className={styles.header}>
      <a className={styles.brand} href="#top" aria-label={ar?'نظام المحاسبة':'Accounting System'}><span className={styles.brandIcon}><Calculator size={24} aria-hidden="true"/></span><div><strong>{ar?'نظام المحاسبة':'Accounting System'}</strong><span>ACCOUNTING & ERP</span></div></a>
      <nav className={styles.topNav} aria-label={ar?'التنقل الرئيسي':'Main navigation'}><a href="#features">{ar?'المزايا':'Features'}</a><a href="#how">{ar?'كيف يعمل':'How it works'}</a><a href="#security">{ar?'الأمان':'Security'}</a><a href="#faq">{ar?'الأسئلة':'FAQ'}</a></nav>
      <button className={styles.language} type="button" onClick={()=>setAr(!ar)} aria-label={ar?'Switch to English':'التبديل إلى العربية'}><Languages size={18} aria-hidden="true"/>{ar?'English':'العربية'}</button>
    </header>
    <div id="top" className={styles.content}>
      <section className={styles.hero} aria-labelledby="welcome-title">
        <span className={styles.eyebrow}>{ar?'منصة محاسبة وإدارة أعمال ثنائية اللغة':'Bilingual accounting & business management'}</span>
        <h1 id="welcome-title">{ar?<>كل حساباتك،<br/><em>في مكان واحد.</em></>:<>Your accounts.<br/><em>All in one place.</em></>}</h1>
        <p className={styles.intro}>{ar?'من المبيعات والمشتريات والمخزون إلى القيود والتقارير والتسويات البنكية — مساحة واحدة منظّمة لإدارة العمليات المالية بوضوح.':'From sales, purchases and inventory to journals, reporting and bank reconciliation — one organised workspace for clearer financial operations.'}</p>
        <div className={styles.features}><span><FileText size={18} aria-hidden="true"/>{ar?'فواتير ومبيعات':'Invoices & sales'}</span><span><Wallet size={18} aria-hidden="true"/>{ar?'حسابات وبنوك':'Accounts & banks'}</span><span><BarChart3 size={18} aria-hidden="true"/>{ar?'تقارير مالية':'Financial reports'}</span></div>
        <div className={styles.trustLine}><span><Languages size={16}/>{ar?'عربي + English':'Arabic + English'}</span><span><Building2 size={16}/>{ar?'متعدد الشركات':'Multi-company'}</span><span><ShieldCheck size={16}/>{ar?'صلاحيات حسب الدور':'Role-based access'}</span></div>
        <div className={styles.art} aria-hidden="true"><div className={styles.orbit}/><div className={styles.artCard}><span/><span/><div className={styles.bars}><i/><i/><i/><i/><i/><i/></div></div><div className={styles.artBadge}><BarChart3 size={24}/><span>{ar?'رؤية أوضح لأعمالك':'Clarity for your business'}</span></div></div>
      </section>
      <section className={styles.panel} aria-labelledby="signin-title">
        <span className={styles.panelIcon}><LockKeyhole size={24} aria-hidden="true"/></span>
        <p className={styles.kicker}>{ar?'دخول آمن إلى مساحة العمل':'SECURE WORKSPACE ACCESS'}</p><h2 id="signin-title">{ar?'تسجيل الدخول':'Sign in'}</h2>
        <p className={styles.panelIntro}>{ar?'أدخل بيانات حسابك للمتابعة إلى البرنامج.':'Enter your account details to continue.'}</p>
        <form onSubmit={submit} className={styles.form}>
          <label htmlFor="login-email">{ar?'البريد الإلكتروني':'Email address'}</label>
          <div className={styles.field}><Mail size={19} aria-hidden="true"/><input id="login-email" required autoComplete="username" type="email" dir="ltr" value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@company.com"/></div>
          <label htmlFor="login-password">{ar?'كلمة المرور':'Password'}</label>
          <div className={styles.field}><LockKeyhole size={19} aria-hidden="true"/><input id="login-password" required autoComplete="current-password" type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder={ar?'أدخل كلمة المرور':'Enter your password'}/></div>
          {error&&<p className={styles.error} role="alert">{ar?'تعذر تسجيل الدخول. تحقق من بياناتك وحاول مجدداً.':error}</p>}
          <button className={styles.submit} type="submit" disabled={busy} aria-busy={busy}>{busy?(ar?'جاري تسجيل الدخول…':'Signing in…'):(ar?'الدخول إلى البرنامج':'Continue to workspace')}<Arrow size={19} aria-hidden="true"/></button>
        </form>
        <p className={styles.help}>{ar?'تحتاج مساعدة؟ بيانات التواصل متاحة أسفل الصفحة.':'Need a hand? Contact details are available below.'}</p>
      </section>
    </div>
    <section id="features" className={styles.marketingSection} aria-labelledby="features-title"><div className={styles.sectionHead}><span>{ar?'منصة متكاملة':'CONNECTED WORKSPACE'}</span><h2 id="features-title">{ar?'الأدوات الأساسية في مكان واحد':'Core business tools in one place'}</h2><p>{ar?'وحدات مترابطة تغطي العمليات اليومية والتقارير والمراجعة دون تشتيت بين أنظمة منفصلة.':'Connected modules for daily operations, reporting and review without jumping between separate systems.'}</p></div><div className={styles.moduleGrid}>{modules.map(([Icon,title,desc])=><article className={styles.moduleCard} key={title}><span><Icon size={22}/></span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
    <section id="how" className={`${styles.marketingSection} ${styles.lightSection}`} aria-labelledby="how-title"><div className={styles.sectionHead}><span>{ar?'تدفق عمل واضح':'CLEAR WORKFLOW'}</span><h2 id="how-title">{ar?'كيف يعمل النظام؟':'How it works'}</h2></div><div className={styles.steps}><article><b>01</b><h3>{ar?'تهيئة الشركة':'Set up the company'}</h3><p>{ar?'تحديد الحسابات والفترات والضرائب والمستودعات والعملات وفق احتياج الشركة.':'Configure accounts, periods, taxes, warehouses and currencies for the company.'}</p></article><article><b>02</b><h3>{ar?'تسجيل العمليات':'Record operations'}</h3><p>{ar?'إدخال المبيعات والمشتريات والمصروفات والمقبوضات والمدفوعات من وحداتها المخصصة.':'Record sales, purchases, expenses, receipts and payments in dedicated workflows.'}</p></article><article><b>03</b><h3>{ar?'الترحيل والمراجعة':'Post & review'}</h3><p>{ar?'ترحيل المستندات إلى القيود ومراجعة الحركة والمخزون والحسابات البنكية.':'Post documents to journals and review ledger, inventory and banking activity.'}</p></article><article><b>04</b><h3>{ar?'قراءة التقارير':'Read the reports'}</h3><p>{ar?'متابعة التقارير المالية والذمم والمخزون لدعم القرار والمراجعة الدورية.':'Use financial, aging and inventory reports for review and better decisions.'}</p></article></div></section>
    <section id="security" className={styles.marketingSection} aria-labelledby="security-title"><div className={styles.securityGrid}><div><div className={styles.sectionHead}><span>{ar?'ثقة مبنية على النظام':'SECURITY & CONTROL'}</span><h2 id="security-title">{ar?'حماية وصلاحيات ومراجعة':'Security, permissions and auditability'}</h2><p>{ar?'النسخة الخادمية مصممة بمصادقة JWT، عضوية شركات وصلاحيات حسب الدور، وكلمات مرور مخزنة كـ bcrypt hash، مع سجل مراجعة وضوابط على القيود المرحلة.':'The server edition uses JWT authentication, company memberships, role permissions and bcrypt password hashes, with audit records and controls around posted journals.'}</p></div><ul className={styles.checkList}><li><CheckCircle2/>{ar?'قيود مرحلة غير قابلة للتعديل المباشر؛ التصحيح يتم بالعكس المحاسبي.':'Posted journals are immutable; corrections use reversals.'}</li><li><CheckCircle2/>{ar?'فصل صلاحيات المالك والمدير والمحاسب والمبيعات والمشتريات والموظف.':'Separate Owner, Admin, Accountant, Sales, Purchases and Employee roles.'}</li><li><CheckCircle2/>{ar?'سياسات عزل بيانات الشركات وضوابط قاعدة بيانات إضافية في النسخة الخادمية.':'Tenant isolation policies and additional database constraints in the server edition.'}</li></ul></div><aside className={styles.securityCard}><ShieldCheck size={34}/><strong>{ar?'مهم':'Important'}</strong><p>{ar?'النسخة المنشورة للمعاينة قد تستخدم بيانات محلية وتجريبية لبعض الوظائف. تشغيل النظام ببيانات أعمال حقيقية يتطلب نشر الخادم وقاعدة البيانات والنسخ الاحتياطي والأسرار بشكل آمن.':'The published preview may use local sample data for some functions. Real business data requires a properly deployed server, database, backups and secret management.'}</p></aside></div></section>
    <section id="faq" className={`${styles.marketingSection} ${styles.lightSection}`} aria-labelledby="faq-title"><div className={styles.sectionHead}><span>FAQ</span><h2 id="faq-title">{ar?'أسئلة شائعة':'Frequently asked questions'}</h2></div><div className={styles.faqGrid}><details><summary>{ar?'هل يدعم العربية والإنجليزية؟':'Does it support Arabic and English?'}</summary><p>{ar?'نعم، واجهة النظام مصممة للعمل بالعربية والإنجليزية مع اتجاه RTL وLTR.':'Yes. The interface supports Arabic and English with RTL and LTR layouts.'}</p></details><details><summary>{ar?'هل يدعم أكثر من شركة؟':'Can it handle more than one company?'}</summary><p>{ar?'نعم، النظام يدعم عضويات متعددة للشركات والتنقل بينها حسب صلاحيات المستخدم.':'Yes. Users can have memberships in multiple companies and switch according to their permissions.'}</p></details><details><summary>{ar?'هل يدعم المخزون والتقارير؟':'Does it include inventory and reporting?'}</summary><p>{ar?'نعم، يتضمن مخزونًا حسب المستودع وتقارير مالية وذمم وتقييم مخزون ضمن النطاق المنفذ.':'Yes. The implemented scope includes warehouse inventory, financial reports, aging and inventory valuation.'}</p></details><details><summary>{ar?'هل يغني عن المحاسب أو المتطلبات الرسمية؟':'Does it replace an accountant or official compliance requirements?'}</summary><p>{ar?'لا. النظام أداة تشغيل ومحاسبة، ويجب التحقق من المتطلبات الضريبية والقانونية والفوترة الإلكترونية حسب الدولة والجهة المختصة.':'No. It is an accounting and operations tool; tax, legal and e-invoicing requirements must be verified for the applicable jurisdiction.'}</p></details></div></section>
    <PlatformLinks ar={ar}/>
    <footer className={styles.footer}><p>{ar?'تصميم':'Designed by'} <strong>{ar?'محمد العقلة':'Mohammed Al-Oqleh'}</strong></p><nav className={styles.contacts} aria-label={ar?'بيانات التواصل':'Contact details'}><a href="tel:+966545506941" aria-label={ar?'الاتصال بمحمد العقلة':'Call Mohammed Al-Oqleh'}><Phone size={16} aria-hidden="true"/><span dir="ltr">+966 545506941</span></a><a href="mailto:info.moqleh@yahoo.com" aria-label={ar?'مراسلة محمد العقلة بالبريد الإلكتروني':'Email Mohammed Al-Oqleh'}><Mail size={17} aria-hidden="true"/><span dir="ltr">info.moqleh@yahoo.com</span></a></nav></footer>
  </main>;
}
