'use client';
import { useEffect, useMemo, useState } from 'react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, getCompanyId } from '@/lib/api';

type FiscalYear={id:string;name:string;status:string;startDate:string;endDate:string;periods:Array<{id:string;number:number;status:string}>;closingJournalId?:string|null};
type Account={id:string;code:string;name:string;type:string;isLeaf:boolean;isActive:boolean};
export default function Page(){return <ErpShell><YearEnd/></ErpShell>}
function YearEnd(){
 const {locale}=useLocale(),ar=locale==='ar',companyId=getCompanyId();
 const [years,setYears]=useState<FiscalYear[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[yearId,setYearId]=useState(''),[retainedId,setRetainedId]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>Promise.all([apiGet<FiscalYear[]>(`/admin/fiscal-years/${companyId}`),apiGet<Account[]>(`/admin/accounts/${companyId}`)]).then(([y,a])=>{setYears(y);setAccounts(a);setYearId(v=>v||y.find(x=>x.status!=='Closed')?.id||'');setRetainedId(v=>v||a.find(x=>x.type==='Equity'&&x.isLeaf&&x.isActive)?.id||'')}).catch(e=>setMessage(e instanceof Error?e.message:String(e)));
 useEffect(()=>{load()},[companyId]);
 const equity=useMemo(()=>accounts.filter(a=>a.type==='Equity'&&a.isLeaf&&a.isActive),[accounts]);const selected=years.find(y=>y.id===yearId);
 const close=async()=>{if(!yearId||!retainedId)return;const ok=confirm(ar?'سيتم إغلاق السنة المالية نهائياً. هل تريد المتابعة؟':'This will permanently close the fiscal year. Continue?');if(!ok)return;setBusy(true);setMessage('');try{const result=await apiPost<{closingJournalId:string|null;netProfit:string}>('/year-end/close',{companyId,fiscalYearId:yearId,retainedEarningsAccountId:retainedId,notes});setMessage(ar?`تم إغلاق السنة. صافي النتيجة: ${result.netProfit}`:`Fiscal year closed. Net result: ${result.netProfit}`);await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <><div className="heading"><div><h1>{ar?'إقفال السنة المالية':'Year-End Closing'}</h1><p>{ar?'إقفال الإيرادات والمصروفات وتحويل النتيجة إلى الأرباح المحتجزة':'Close revenue and expense accounts and transfer the result to retained earnings'}</p></div></div>{message&&<div className="card formMessage">{message}</div>}<section className="gridTwo"><div className="card"><h3>{ar?'إجراء الإقفال':'Closing Action'}</h3><label>{ar?'السنة المالية':'Fiscal year'}<select value={yearId} onChange={e=>setYearId(e.target.value)}><option value="">—</option>{years.map(y=><option key={y.id} value={y.id}>{y.name} — {y.status}</option>)}</select></label><label>{ar?'حساب الأرباح المحتجزة':'Retained earnings account'}<select value={retainedId} onChange={e=>setRetainedId(e.target.value)}><option value="">—</option>{equity.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>{ar?'ملاحظات':'Notes'}<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4}/></label><button className="primary" disabled={busy||!yearId||selected?.status==='Closed'} onClick={close}>{busy?(ar?'جاري الإقفال...':'Closing...'):(ar?'إقفال السنة':'Close Fiscal Year')}</button></div><div className="card"><h3>{ar?'شروط الإقفال':'Closing Requirements'}</h3><p>{ar?'يجب أن تكون جميع الفترات السابقة مقفلة إقفالاً نهائياً، وتبقى الفترة الأخيرة مفتوحة حتى إنشاء قيد الإقفال.':'All earlier periods must be hard closed and the final period remains open until the closing journal is posted.'}</p><p>{ar?'بعد الإقفال لا يمكن الترحيل على السنة بالطريقة الاعتيادية.':'After closing, ordinary posting to the fiscal year is blocked.'}</p>{selected&&<div className="settingLine"><b>{selected.name}</b><span>{selected.startDate.slice(0,10)} — {selected.endDate.slice(0,10)}</span><span className={`status ${selected.status==='Closed'?'overdue':'paid'}`}>{selected.status}</span></div>}</div></section><section className="card"><div className="cardTitle"><h2>{ar?'السنوات المالية':'Fiscal Years'}</h2></div><div className="tableWrap"><table><thead><tr><th>{ar?'السنة':'Year'}</th><th>{ar?'من':'Start'}</th><th>{ar?'إلى':'End'}</th><th>{ar?'الحالة':'Status'}</th><th>{ar?'قيد الإقفال':'Closing Journal'}</th></tr></thead><tbody>{years.map(y=><tr key={y.id}><td>{y.name}</td><td>{y.startDate.slice(0,10)}</td><td>{y.endDate.slice(0,10)}</td><td>{y.status}</td><td>{y.closingJournalId??'—'}</td></tr>)}</tbody></table></div></section></>;
}
