'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { CircleDollarSign, TrendingDown, TrendingUp, WalletCards } from 'lucide-react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, getCompanyId, getSession } from '@/lib/api';

type DashboardData={sales:string;purchases:string;customers:number;suppliers:number;items:number;journals:number;baseCurrencyCode:string};
type Invoice={id:string;invoiceNumber:string;invoiceDate:string;grandTotal:string;status:string;currencyCode?:string;customer:{name:string}};

export default function Home(){return <ErpShell><Dashboard/></ErpShell>}
function Dashboard(){
  const {locale}=useLocale(); const ar=locale==='ar';
  const [data,setData]=useState<DashboardData|null>(null); const [invoices,setInvoices]=useState<Invoice[]>([]); const [offline,setOffline]=useState(false);
  const companyId=getCompanyId();const companyName=getSession()?.memberships.find(m=>m.companyId===companyId)?.companyName??(ar?'الشركة':'Company');
  useEffect(()=>{Promise.all([apiGet<DashboardData>(`/erp/dashboard/${companyId}`),apiGet<Invoice[]>(`/erp/sales/${companyId}`)]).then(([d,i])=>{setData(d);setInvoices(i.slice(0,5));setOffline(false)}).catch(()=>setOffline(true))},[companyId]);
  const sales=data?.sales??'0',purchases=data?.purchases??'0',currency=data?.baseCurrencyCode??'';
  const profit=useMemo(()=>{const s=Number(sales),p=Number(purchases);return Number.isFinite(s-p)?String(s-p):'0'},[sales,purchases]);
  const comparison=useMemo(()=>{const s=Math.max(0,Number(sales)||0),p=Math.max(0,Number(purchases)||0),max=Math.max(s,p,1);return [{label:ar?'المبيعات':'Sales',value:s,height:Math.max(8,(s/max)*100)},{label:ar?'المشتريات':'Purchases',value:p,height:Math.max(8,(p/max)*100)}]},[sales,purchases,ar]);
  return <><div className="heading"><div><h1>{ar?'لوحة التحكم':'Dashboard'}</h1><p>{companyName} {offline&&<span className="demoBadge">{ar?'تعذر تحديث البيانات':'Data unavailable'}</span>}</p></div><Link className="primary" href="/sales/new">+ {ar?'فاتورة جديدة':'New Invoice'}</Link></div>
    <section className="kpis"><Kpi title={ar?'إجمالي المبيعات':'Total Sales'} value={`${format(sales)} ${currency}`} delta={ar?'بالعملة الأساسية':'Base currency'} positive icon={<TrendingUp/>}/><Kpi title={ar?'المشتريات':'Total Purchases'} value={`${format(purchases)} ${currency}`} delta={ar?'بالعملة الأساسية':'Base currency'} icon={<TrendingDown/>}/><Kpi title={ar?'فرق المبيعات والمشتريات':'Sales less purchases'} value={`${format(profit)} ${currency}`} delta={ar?'المبيعات ناقص المشتريات':'Sales less purchases'} positive icon={<CircleDollarSign/>}/><Kpi title={ar?'القيود المرحلة':'Posted Journals'} value={String(data?.journals??0)} delta={ar?`${data?.customers??0} عملاء · ${data?.suppliers??0} موردين`:`${data?.customers??0} customers · ${data?.suppliers??0} suppliers`} icon={<WalletCards/>}/></section>
    <section className="gridTwo"><div className="card chartCard"><div className="cardTitle"><h2>{ar?'مقارنة النشاط':'Activity Comparison'}</h2><span>{currency}</span></div><div className="chart">{comparison.map((v,i)=><div className="barWrap" key={v.label}><div className="bar" style={{height:`${v.height}%`}} title={`${format(String(v.value))} ${currency}`}/><span>{i===0?(ar?'بيع':'S'):(ar?'شراء':'P')}</span></div>)}</div></div><div className="card alerts"><div className="cardTitle"><h2>{ar?'مراجعة سريعة':'Quick Review'}</h2></div><QuickLink href="/reports/customer-aging" label={ar?'أعمار ذمم العملاء':'Customer aging'}/><QuickLink href="/reports/inventory-valuation" label={ar?'تقييم المخزون':'Inventory valuation'}/><QuickLink href="/banking" label={ar?'التسويات البنكية':'Bank reconciliations'}/></div></section>
    <section className="card tableCard"><div className="cardTitle"><h2>{ar?'أحدث الفواتير':'Recent Invoices'}</h2><Link className="ghost" href="/sales">{ar?'عرض الكل':'View all'}</Link></div><div className="tableWrap"><table><thead><tr><th>{ar?'رقم الفاتورة':'Invoice #'}</th><th>{ar?'العميل':'Customer'}</th><th>{ar?'التاريخ':'Date'}</th><th>{ar?'المبلغ':'Amount'}</th><th>{ar?'الحالة':'Status'}</th></tr></thead><tbody>{invoices.length?invoices.map(i=><Row key={i.id} id={i.invoiceNumber} customer={i.customer.name} date={i.invoiceDate.slice(0,10)} amount={`${format(i.grandTotal)} ${i.currencyCode??currency}`} status={translateStatus(i.status,ar)} cls={i.status==='Posted'?'paid':'partial'}/>):<tr><td colSpan={5}>{ar?'لا توجد فواتير بعد':'No invoices yet'}</td></tr>}</tbody></table></div></section></>}
function format(value:string){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n):value}
function translateStatus(status:string,ar:boolean){if(!ar)return status;return status==='Posted'?'مرحلة':status==='Draft'?'مسودة':status==='Cancelled'?'ملغاة':status}
function Kpi({title,value,delta,positive,icon}:{title:string;value:string;delta:string;positive?:boolean;icon:ReactNode}){return <article className="kpi"><div className="kpiIcon">{icon}</div><div><small>{title}</small><strong>{value}</strong><span className={positive?'positive':'muted'}>{delta}</span></div></article>}
function QuickLink({href,label}:{href:string;label:string}){return <Link className="alertRow" href={href}><div className="alertIcon">→</div><span>{label}</span><b>›</b></Link>}
function Row({id,customer,date,amount,status,cls}:{id:string;customer:string;date:string;amount:string;status:string;cls:string}){return <tr><td>{id}</td><td>{customer}</td><td>{date}</td><td>{amount}</td><td><span className={`status ${cls}`}>{status}</span></td></tr>}
