'use client';
import Link from 'next/link';
import { CircleDollarSign, TrendingDown, TrendingUp, WalletCards } from 'lucide-react';
import { ErpShell, useLocale } from '@/components/erp-shell';
const chart=[38,45,52,48,63,58,70,66,77,74,86,82];
export default function Home(){return <ErpShell><Dashboard/></ErpShell>}
function Dashboard(){const {locale}=useLocale();const ar=locale==='ar';return <><div className="heading"><div><h1>{ar?'لوحة التحكم':'Dashboard'}</h1><p>{ar?'شركة المثال للتجارة':'Example Trading Company'}</p></div><Link className="primary" href="/sales/new">+ {ar?'فاتورة جديدة':'New Invoice'}</Link></div><section className="kpis"><Kpi title={ar?'إجمالي المبيعات':'Total Sales'} value="128,450 SAR" delta="+12.4%" positive icon={<TrendingUp/>}/><Kpi title={ar?'المصروفات':'Total Expenses'} value="42,300 SAR" delta="-3.2%" icon={<TrendingDown/>}/><Kpi title={ar?'صافي الربح':'Net Profit'} value="86,150 SAR" delta="+8.7%" positive icon={<CircleDollarSign/>}/><Kpi title={ar?'المستحقات':'Receivables'} value="17,800 SAR" delta={ar?'6 فواتير':'6 invoices'} icon={<WalletCards/>}/></section><section className="gridTwo"><div className="card chartCard"><div className="cardTitle"><h2>{ar?'المبيعات والمصروفات':'Sales & Expenses'}</h2><span>2026</span></div><div className="chart">{chart.map((v,i)=><div className="barWrap" key={i}><div className="bar" style={{height:`${v}%`}}/><span>{i+1}</span></div>)}</div></div><div className="card alerts"><div className="cardTitle"><h2>{ar?'تنبيهات':'Alerts'}</h2></div><Alert count="6" label={ar?'فواتير متأخرة السداد':'Overdue invoices'}/><Alert count="4" label={ar?'منتجات منخفضة المخزون':'Low stock products'}/><Alert count="2" label={ar?'تسويات بنكية معلقة':'Pending bank reconciliations'}/></div></section><section className="card tableCard"><div className="cardTitle"><h2>{ar?'أحدث الفواتير':'Recent Invoices'}</h2><Link className="ghost" href="/sales">{ar?'عرض الكل':'View all'}</Link></div><div className="tableWrap"><table><thead><tr><th>{ar?'رقم الفاتورة':'Invoice #'}</th><th>{ar?'العميل':'Customer'}</th><th>{ar?'التاريخ':'Date'}</th><th>{ar?'المبلغ':'Amount'}</th><th>{ar?'الحالة':'Status'}</th></tr></thead><tbody><Row id="INV-0012" customer={ar?'مؤسسة النور':'Al Noor Company'} amount="12,450" status={ar?'مدفوعة':'Paid'} cls="paid"/><Row id="INV-0011" customer={ar?'شركة الأمل':'Al Amal Co.'} amount="7,300" status={ar?'جزئية':'Partial'} cls="partial"/><Row id="INV-0010" customer={ar?'شركة النخبة':'Elite Company'} amount="8,900" status={ar?'متأخرة':'Overdue'} cls="overdue"/></tbody></table></div></section></>}
function Kpi({title,value,delta,positive,icon}:{title:string;value:string;delta:string;positive?:boolean;icon:React.ReactNode}){return <article className="kpi"><div className="kpiIcon">{icon}</div><div><small>{title}</small><strong>{value}</strong><span className={positive?'positive':'muted'}>{delta}</span></div></article>}
function Alert({count,label}:{count:string;label:string}){return <div className="alertRow"><div className="alertIcon">!</div><span>{label}</span><b>{count}</b></div>}
function Row({id,customer,amount,status,cls}:{id:string;customer:string;amount:string;status:string;cls:string}){return <tr><td>{id}</td><td>{customer}</td><td>2026-09-10</td><td>{amount}</td><td><span className={`status ${cls}`}>{status}</span></td></tr>}
