'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { Plus,Search,Undo2 } from 'lucide-react';
import { ErpShell,useLocale } from '@/components/erp-shell';
import { apiGet,getCompanyId } from '@/lib/api';
type Bill={id:string;billNumber:string;billDate:string;grandTotal:string;status:string;currencyCode?:string;supplier:{name:string}};
export default function Page(){return <ErpShell><PurchaseList/></ErpShell>}
function PurchaseList(){const {locale}=useLocale(),ar=locale==='ar',companyId=getCompanyId();const [rows,setRows]=useState<Bill[]>([]),[q,setQ]=useState(''),[error,setError]=useState('');useEffect(()=>{apiGet<Bill[]>(`/erp/purchases/${companyId}`).then(setRows).catch(e=>setError(e instanceof Error?e.message:String(e)))},[companyId]);const filtered=rows.filter(r=>`${r.billNumber} ${r.supplier.name}`.toLowerCase().includes(q.toLowerCase()));return <><div className="heading"><div><h1>{ar?'المشتريات':'Purchases'}</h1><p>{ar?'فواتير الموردين والاستلام والتكاليف والمرتجعات':'Supplier bills, receipts, costs and returns'}</p></div><div className="formActions"><Link className="ghost" href="/purchases/debit-notes"><Undo2 size={17}/>{ar?'مرتجعات المشتريات':'Purchase Returns'}</Link><Link className="primary" href="/purchases/new"><Plus size={17}/>{ar?'فاتورة شراء':'New Purchase Bill'}</Link></div></div><section className="card"><div className="moduleToolbar"><div className="inlineSearch"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث في المشتريات...':'Search purchases...'}/></div></div>{error&&<div className="formMessage">{error}</div>}<div className="tableWrap"><table><thead><tr><th>{ar?'رقم الفاتورة':'Bill #'}</th><th>{ar?'المورد':'Supplier'}</th><th>{ar?'التاريخ':'Date'}</th><th>{ar?'الإجمالي':'Total'}</th><th>{ar?'الحالة':'Status'}</th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id}><td>{r.billNumber}</td><td>{r.supplier.name}</td><td>{r.billDate.slice(0,10)}</td><td>{format(r.grandTotal)} {r.currencyCode??''}</td><td><span className={`status ${r.status==='Posted'?'paid':'partial'}`}>{ar?translate(r.status):r.status}</span></td></tr>):<tr><td colSpan={5}>{ar?'لا توجد مشتريات بعد':'No purchases yet'}</td></tr>}</tbody></table></div></section></>}
function format(v:string){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n):v}function translate(s:string){return s==='Posted'?'مرحلة':s==='Draft'?'مسودة':s==='Cancelled'?'ملغاة':s}
