'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, DEMO_COMPANY_ID } from '@/lib/api';

type Customer={id:string;name:string}; type Warehouse={id:string;name:string}; type Item={id:string;code:string;name:string}; type TaxRate={id:string;name:string;rate:string};
type Line={itemId:string;quantity:string;unitPrice:string;taxRateId?:string};

export default function Page(){return <ErpShell><InvoiceForm/></ErpShell>}
function InvoiceForm(){
  const {locale}=useLocale(); const ar=locale==='ar'; const router=useRouter();
  const [customers,setCustomers]=useState<Customer[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[items,setItems]=useState<Item[]>([]),[taxes,setTaxes]=useState<TaxRate[]>([]);
  const [customerId,setCustomerId]=useState(''),[warehouseId,setWarehouseId]=useState(''),[date,setDate]=useState('2026-09-11'),[currency,setCurrency]=useState('SAR');
  const [lines,setLines]=useState<Line[]>([{itemId:'',quantity:'1',unitPrice:'0'}]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{Promise.all([apiGet<Customer[]>(`/erp/customers/${DEMO_COMPANY_ID}`),apiGet<Warehouse[]>(`/erp/warehouses/${DEMO_COMPANY_ID}`),apiGet<Item[]>(`/erp/items/${DEMO_COMPANY_ID}`),apiGet<TaxRate[]>(`/erp/tax-rates/${DEMO_COMPANY_ID}`)]).then(([c,w,i,t])=>{setCustomers(c);setWarehouses(w);setItems(i);setTaxes(t);setCustomerId(c[0]?.id??'');setWarehouseId(w[0]?.id??'');setLines([{itemId:i[0]?.id??'',quantity:'1',unitPrice:'0',taxRateId:t[0]?.id}])}).catch(()=>setMessage(ar?'تعذر الاتصال بالخادم. شغّل API وقاعدة البيانات.':'Could not connect to the API. Start the API and database.'))},[ar]);
  const totals=useMemo(()=>lines.reduce((a,l)=>{const q=Number(l.quantity)||0,p=Number(l.unitPrice)||0;const tax=taxes.find(t=>t.id===l.taxRateId);const rate=Number(tax?.rate??0);const net=q*p;return {net:a.net+net,tax:a.tax+net*rate}}, {net:0,tax:0}),[lines,taxes]);
  const update=(index:number,key:keyof Line,value:string)=>setLines(v=>v.map((l,i)=>i===index?{...l,[key]:value}:l));
  const submit=async()=>{if(!customerId||!warehouseId||lines.some(l=>!l.itemId)){setMessage(ar?'أكمل بيانات الفاتورة':'Complete the invoice details');return}setBusy(true);setMessage('');try{await apiPost('/sales/invoice',{companyId:DEMO_COMPANY_ID,customerId,warehouseId,invoiceDate:`${date}T12:00:00Z`,currencyCode:currency,exchangeRate:'1',lines});setMessage(ar?'تم ترحيل الفاتورة بنجاح':'Invoice posted successfully');setTimeout(()=>router.push('/sales'),700)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  return <><div className="heading"><div><h1>{ar?'إنشاء فاتورة جديدة':'Create New Invoice'}</h1><p>{ar?'أدخل بيانات العميل والمنتجات ثم رحّل الفاتورة':'Enter customer and product details, then post the invoice'}</p></div></div><section className="card invoiceForm"><div className="formGrid"><label>{ar?'العميل':'Customer'}<select value={customerId} onChange={e=>setCustomerId(e.target.value)}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{ar?'التاريخ':'Date'}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{ar?'العملة':'Currency'}<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>SAR</option><option>USD</option></select></label><label>{ar?'المستودع':'Warehouse'}<select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></div><div className="tableWrap"><table><thead><tr><th>{ar?'المنتج':'Product'}</th><th>{ar?'الكمية':'Qty'}</th><th>{ar?'سعر الوحدة':'Unit Price'}</th><th>{ar?'الضريبة':'Tax'}</th><th>{ar?'الإجمالي':'Total'}</th><th></th></tr></thead><tbody>{lines.map((line,index)=>{const tax=taxes.find(t=>t.id===line.taxRateId);const total=(Number(line.quantity)||0)*(Number(line.unitPrice)||0)*(1+Number(tax?.rate??0));return <tr key={index}><td><select value={line.itemId} onChange={e=>update(index,'itemId',e.target.value)}>{items.map(i=><option key={i.id} value={i.id}>{i.code} — {i.name}</option>)}</select></td><td><input className="cellInput" value={line.quantity} onChange={e=>update(index,'quantity',e.target.value)}/></td><td><input className="cellInput" value={line.unitPrice} onChange={e=>update(index,'unitPrice',e.target.value)}/></td><td><select value={line.taxRateId??''} onChange={e=>update(index,'taxRateId',e.target.value)}><option value="">0%</option>{taxes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></td><td>{total.toFixed(2)}</td><td><button className="ghost" onClick={()=>setLines(v=>v.filter((_,i)=>i!==index))}>×</button></td></tr>})}</tbody></table></div><button className="ghost" onClick={()=>setLines(v=>[...v,{itemId:items[0]?.id??'',quantity:'1',unitPrice:'0',taxRateId:taxes[0]?.id}])}>+ {ar?'إضافة منتج':'Add Product'}</button><div className="invoiceSummary"><div><span>{ar?'المجموع الفرعي':'Subtotal'}</span><b>{totals.net.toFixed(2)} {currency}</b></div><div><span>{ar?'الضريبة':'Tax'}</span><b>{totals.tax.toFixed(2)} {currency}</b></div><div className="grand"><span>{ar?'الإجمالي الكلي':'Grand Total'}</span><b>{(totals.net+totals.tax).toFixed(2)} {currency}</b></div></div>{message&&<div className="formMessage">{message}</div>}<div className="formActions"><button className="ghost" onClick={()=>router.back()}>{ar?'إلغاء':'Cancel'}</button><button className="primary" disabled={busy} onClick={submit}>{busy?(ar?'جاري الترحيل...':'Posting...'):(ar?'حفظ وترحيل':'Save & Post')}</button></div></section></>}
