'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, getCompanyId, idempotencyHeaders } from '@/lib/api';

type Account={id:string;code:string;name:string;type:string;isLeaf:boolean;isActive:boolean};
type Line={accountId:string;debit:string;credit:string;description:string};
export default function Page(){return <ErpShell><ManualJournal/></ErpShell>}
function ManualJournal(){
 const {locale}=useLocale(),ar=locale==='ar',router=useRouter(),companyId=getCompanyId();const [accounts,setAccounts]=useState<Account[]>([]),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[reference,setReference]=useState(''),[lines,setLines]=useState<Line[]>([{accountId:'',debit:'0',credit:'',description:''},{accountId:'',debit:'',credit:'0',description:''}]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{apiGet<Account[]>(`/admin/accounts/${companyId}`).then(a=>{const leaf=a.filter(x=>x.isLeaf&&x.isActive);setAccounts(leaf);setLines(v=>v.map((l,i)=>({...l,accountId:l.accountId||leaf[i]?.id||leaf[0]?.id||''})))}).catch(e=>setMessage(e instanceof Error?e.message:String(e)))},[companyId]);
 const totals=useMemo(()=>lines.reduce((a,l)=>({d:a.d+(Number(l.debit)||0),c:a.c+(Number(l.credit)||0)}),{d:0,c:0}),[lines]);
 const update=(i:number,key:keyof Line,value:string)=>setLines(v=>v.map((l,n)=>n===i?{...l,[key]:value}:l));
 const submit=async()=>{if(lines.length<2||lines.some(l=>!l.accountId)){setMessage(ar?'أدخل سطرين على الأقل':'Enter at least two lines');return}if(Math.abs(totals.d-totals.c)>0.0001){setMessage(ar?'القيد غير متوازن':'Journal is not balanced');return}setBusy(true);setMessage('');try{await apiPost('/accounting/journals/manual',{companyId,transactionDate:`${date}T12:00:00Z`,reference,lines:lines.map(l=>({accountId:l.accountId,debit:l.debit||undefined,credit:l.credit||undefined,description:l.description||undefined}))},idempotencyHeaders());router.push('/journals')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <><div className="heading"><div><h1>{ar?'قيد يومية جديد':'New Journal Entry'}</h1><p>{ar?'قيد يدوي مزدوج مع ترقيم تلقائي وترحيل آمن':'Manual double-entry journal with automatic numbering and safe posting'}</p></div></div><section className="card invoiceForm"><div className="formGrid"><label>{ar?'التاريخ':'Date'}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{ar?'المرجع':'Reference'}<input value={reference} onChange={e=>setReference(e.target.value)}/></label></div><div className="tableWrap"><table><thead><tr><th>{ar?'الحساب':'Account'}</th><th>{ar?'مدين':'Debit'}</th><th>{ar?'دائن':'Credit'}</th><th>{ar?'البيان':'Description'}</th><th></th></tr></thead><tbody>{lines.map((l,i)=><tr key={i}><td><select value={l.accountId} onChange={e=>update(i,'accountId',e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></td><td><input className="cellInput" inputMode="decimal" value={l.debit} onChange={e=>update(i,'debit',e.target.value)}/></td><td><input className="cellInput" inputMode="decimal" value={l.credit} onChange={e=>update(i,'credit',e.target.value)}/></td><td><input value={l.description} onChange={e=>update(i,'description',e.target.value)}/></td><td><button className="ghost" disabled={lines.length<=2} onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))}>×</button></td></tr>)}</tbody></table></div><button className="ghost" onClick={()=>setLines(v=>[...v,{accountId:accounts[0]?.id??'',debit:'',credit:'',description:''}])}>+ {ar?'إضافة سطر':'Add Line'}</button><div className="invoiceSummary"><div><span>{ar?'إجمالي المدين':'Total Debit'}</span><b>{totals.d.toFixed(2)}</b></div><div><span>{ar?'إجمالي الدائن':'Total Credit'}</span><b>{totals.c.toFixed(2)}</b></div></div>{message&&<div className="formMessage">{message}</div>}<div className="formActions"><button className="ghost" onClick={()=>router.back()}>{ar?'إلغاء':'Cancel'}</button><button className="primary" disabled={busy} onClick={submit}>{busy?(ar?'جاري الترحيل...':'Posting...'):(ar?'حفظ وترحيل':'Save & Post')}</button></div></section></>;
}
