'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPatch, apiPost, getCompanyId } from '@/lib/api';

type Account={id:string;code:string;name:string;type:string;isLeaf:boolean;isActive:boolean};
type TaxRate={id:string;code:string;name:string;rate:string;effectiveFrom:string;salesTaxAccount:{code:string};purchaseTaxAccount:{code:string}};
type Warehouse={id:string;code:string;name:string;isActive:boolean};
type Period={id:string;number:number;startDate:string;endDate:string;status:'Open'|'Soft_Closed'|'Hard_Closed'};
type FiscalYear={id:string;name:string;startDate:string;endDate:string;status:string;periods:Period[]};

export default function Page(){return <ErpShell><Setup/></ErpShell>}
function Setup(){
 const {locale}=useLocale(),ar=locale==='ar',companyId=getCompanyId();
 const [accounts,setAccounts]=useState<Account[]>([]),[taxes,setTaxes]=useState<TaxRate[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[years,setYears]=useState<FiscalYear[]>([]),[message,setMessage]=useState('');
 const [acc,setAcc]=useState({code:'',name:'',type:'Asset'}),[wh,setWh]=useState({code:'',name:''}),[fy,setFy]=useState({name:'',startDate:'',endDate:''}),[tax,setTax]=useState({code:'VAT15',name:'VAT 15%',rate:'0.15',salesTaxAccountId:'',purchaseTaxAccountId:'',effectiveFrom:new Date().toISOString().slice(0,10)});
 const load=()=>Promise.all([apiGet<Account[]>(`/admin/accounts/${companyId}`),apiGet<TaxRate[]>(`/admin/tax-rates/${companyId}`),apiGet<Warehouse[]>(`/admin/warehouses/${companyId}`),apiGet<FiscalYear[]>(`/admin/fiscal-years/${companyId}`)]).then(([a,t,w,y])=>{setAccounts(a);setTaxes(t);setWarehouses(w);setYears(y);setTax(v=>({...v,salesTaxAccountId:v.salesTaxAccountId||a.find(x=>x.type==='Liability'&&x.isLeaf)?.id||'',purchaseTaxAccountId:v.purchaseTaxAccountId||a.find(x=>x.type==='Asset'&&x.isLeaf)?.id||''}))}).catch(e=>setMessage(e instanceof Error?e.message:String(e)));
 useEffect(()=>{load()},[companyId]);
 const leaf=useMemo(()=>accounts.filter(a=>a.isLeaf&&a.isActive),[accounts]);
 const submit=async(e:FormEvent,kind:'account'|'warehouse'|'year'|'tax')=>{e.preventDefault();setMessage('');try{if(kind==='account')await apiPost(`/admin/accounts/${companyId}`,acc);if(kind==='warehouse')await apiPost(`/admin/warehouses/${companyId}`,wh);if(kind==='year')await apiPost(`/admin/fiscal-years/${companyId}`,fy);if(kind==='tax')await apiPost(`/admin/tax-rates/${companyId}`,tax);setMessage(ar?'تم الحفظ بنجاح':'Saved successfully');await load()}catch(err){setMessage(err instanceof Error?err.message:String(err))}};
 const periodStatus=async(p:Period,status:Period['status'])=>{try{await apiPatch(`/admin/fiscal-periods/${companyId}/${p.id}/status`,{status});await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}};
 return <><div className="heading"><div><h1>{ar?'تهيئة النظام المحاسبي':'Accounting Setup'}</h1><p>{ar?'دليل الحسابات والضرائب والمستودعات والسنوات والفترات المالية':'Chart of accounts, tax, warehouses, fiscal years and periods'}</p></div></div>{message&&<div className="card formMessage">{message}</div>}
 <section className="settingsGrid">
  <form className="card" onSubmit={e=>submit(e,'account')}><h3>{ar?'إضافة حساب':'Add Account'}</h3><label>{ar?'الرمز':'Code'}<input required value={acc.code} onChange={e=>setAcc({...acc,code:e.target.value})}/></label><label>{ar?'الاسم':'Name'}<input required value={acc.name} onChange={e=>setAcc({...acc,name:e.target.value})}/></label><label>{ar?'النوع':'Type'}<select value={acc.type} onChange={e=>setAcc({...acc,type:e.target.value})}>{['Asset','Liability','Equity','Revenue','Expense'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary">{ar?'إضافة الحساب':'Add Account'}</button></form>
  <form className="card" onSubmit={e=>submit(e,'warehouse')}><h3>{ar?'إضافة مستودع':'Add Warehouse'}</h3><label>{ar?'الرمز':'Code'}<input required value={wh.code} onChange={e=>setWh({...wh,code:e.target.value})}/></label><label>{ar?'الاسم':'Name'}<input required value={wh.name} onChange={e=>setWh({...wh,name:e.target.value})}/></label><button className="primary">{ar?'إضافة المستودع':'Add Warehouse'}</button><div className="settingLine">{warehouses.map(w=><span key={w.id}>{w.code} — {w.name}</span>)}</div></form>
  <form className="card" onSubmit={e=>submit(e,'tax')}><h3>{ar?'إضافة ضريبة':'Add Tax Rate'}</h3><label>{ar?'الرمز':'Code'}<input required value={tax.code} onChange={e=>setTax({...tax,code:e.target.value})}/></label><label>{ar?'الاسم':'Name'}<input required value={tax.name} onChange={e=>setTax({...tax,name:e.target.value})}/></label><label>{ar?'النسبة (مثال 0.15)':'Rate (e.g. 0.15)'}<input required value={tax.rate} onChange={e=>setTax({...tax,rate:e.target.value})}/></label><label>{ar?'حساب ضريبة المبيعات':'Sales tax account'}<select value={tax.salesTaxAccountId} onChange={e=>setTax({...tax,salesTaxAccountId:e.target.value})}>{leaf.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>{ar?'حساب ضريبة المشتريات':'Purchase tax account'}<select value={tax.purchaseTaxAccountId} onChange={e=>setTax({...tax,purchaseTaxAccountId:e.target.value})}>{leaf.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>{ar?'ساري من':'Effective from'}<input type="date" value={tax.effectiveFrom} onChange={e=>setTax({...tax,effectiveFrom:e.target.value})}/></label><button className="primary">{ar?'إضافة الضريبة':'Add Tax'}</button></form>
  <form className="card" onSubmit={e=>submit(e,'year')}><h3>{ar?'سنة مالية جديدة':'New Fiscal Year'}</h3><label>{ar?'الاسم':'Name'}<input required value={fy.name} onChange={e=>setFy({...fy,name:e.target.value})}/></label><label>{ar?'من':'Start'}<input required type="date" value={fy.startDate} onChange={e=>setFy({...fy,startDate:e.target.value})}/></label><label>{ar?'إلى':'End'}<input required type="date" value={fy.endDate} onChange={e=>setFy({...fy,endDate:e.target.value})}/></label><button className="primary">{ar?'إنشاء السنة':'Create Fiscal Year'}</button></form>
 </section>
 <section className="card"><div className="cardTitle"><h2>{ar?'الفترات المالية':'Fiscal Periods'}</h2></div>{years.map(y=><div key={y.id}><h3>{y.name} — {y.status}</h3><div className="tableWrap"><table><thead><tr><th>#</th><th>{ar?'من':'Start'}</th><th>{ar?'إلى':'End'}</th><th>{ar?'الحالة':'Status'}</th><th>{ar?'تغيير':'Change'}</th></tr></thead><tbody>{y.periods.map(p=><tr key={p.id}><td>{p.number}</td><td>{p.startDate.slice(0,10)}</td><td>{p.endDate.slice(0,10)}</td><td>{p.status}</td><td><select value={p.status} disabled={y.status==='Closed'} onChange={e=>periodStatus(p,e.target.value as Period['status'])}><option>Open</option><option>Soft_Closed</option><option>Hard_Closed</option></select></td></tr>)}</tbody></table></div></div>)}</section>
 <section className="card"><div className="cardTitle"><h2>{ar?'دليل الحسابات':'Chart of Accounts'}</h2></div><div className="tableWrap"><table><thead><tr><th>{ar?'الرمز':'Code'}</th><th>{ar?'الاسم':'Name'}</th><th>{ar?'النوع':'Type'}</th><th>{ar?'مرحّل إليه':'Postable'}</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.code}</td><td>{a.name}</td><td>{a.type}</td><td>{a.isLeaf?(ar?'نعم':'Yes'):(ar?'لا':'No')}</td></tr>)}</tbody></table></div></section>
 <section className="card"><div className="cardTitle"><h2>{ar?'الضرائب المعرفة':'Configured Taxes'}</h2></div><div className="tableWrap"><table><thead><tr><th>{ar?'الرمز':'Code'}</th><th>{ar?'الاسم':'Name'}</th><th>{ar?'النسبة':'Rate'}</th><th>{ar?'ساري من':'Effective'}</th></tr></thead><tbody>{taxes.map(t=><tr key={t.id}><td>{t.code}</td><td>{t.name}</td><td>{(Number(t.rate)*100).toFixed(2)}%</td><td>{t.effectiveFrom.slice(0,10)}</td></tr>)}</tbody></table></div></section>
 </>;
}
