'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, getCompanyId, idempotencyHeaders } from '@/lib/api';

type InvoiceLine={id:string;quantity:string;unitPrice:string;item:{code:string;name:string}};
type Invoice={id:string;invoiceNumber:string;status:string;customer:{name:string};lines:InvoiceLine[]};
type Warehouse={id:string;name:string};
export default function Page(){return <ErpShell><Body/></ErpShell>}
function Body(){const {locale}=useLocale();const ar=locale==='ar';const router=useRouter();const params=useSearchParams();const companyId=getCompanyId();const [invoices,setInvoices]=useState<Invoice[]>([]);const [warehouses,setWarehouses]=useState<Warehouse[]>([]);const [invoiceId,setInvoiceId]=useState(params.get('invoiceId')??'');const [warehouseId,setWarehouseId]=useState('');const [reason,setReason]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [qty,setQty]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{Promise.all([apiGet<Invoice[]>(`/erp/sales/${companyId}`),apiGet<Warehouse[]>(`/erp/warehouses/${companyId}`)]).then(([i,w])=>{const posted=i.filter(x=>x.status==='Posted');setInvoices(posted);setWarehouses(w);setWarehouseId(w[0]?.id??'');if(!invoiceId)setInvoiceId(posted[0]?.id??'')}).catch(e=>setMessage(e instanceof Error?e.message:String(e)))},[companyId]);
  const invoice=useMemo(()=>invoices.find(i=>i.id===invoiceId),[invoices,invoiceId]);
  const lines=invoice?.lines??[];
  const submit=async()=>{const selected=lines.map(l=>({invoiceLineId:l.id,quantity:qty[l.id]??'0'})).filter(l=>Number(l.quantity)>0);if(!invoiceId||!warehouseId||!reason.trim()||!selected.length){setMessage(ar?'اختر الفاتورة والمستودع وأدخل سبباً وكمية مرتجعة':'Choose invoice, warehouse, reason and return quantity');return}setBusy(true);setMessage('');try{await apiPost('/credit-notes',{companyId,invoiceId,warehouseId,creditDate:`${date}T12:00:00Z`,currencyCode:'SAR',exchangeRate:'1',reason,lines:selected},idempotencyHeaders());router.push('/sales/credit-notes')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  return <><div className="heading"><div><h1>{ar?'مرتجع / إشعار دائن جديد':'New Return / Credit Note'}</h1><p>{ar?'الكمية لا يمكن أن تتجاوز الفاتورة الأصلية أو المرتجعات السابقة':'Quantity cannot exceed the original invoice less prior returns'}</p></div></div><section className="card invoiceForm"><div className="formGrid"><label>{ar?'الفاتورة':'Invoice'}<select value={invoiceId} onChange={e=>{setInvoiceId(e.target.value);setQty({})}}>{invoices.map(i=><option key={i.id} value={i.id}>{i.invoiceNumber} — {i.customer.name}</option>)}</select></label><label>{ar?'التاريخ':'Date'}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{ar?'المستودع':'Warehouse'}<select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>{ar?'السبب':'Reason'}<input value={reason} onChange={e=>setReason(e.target.value)} placeholder={ar?'سبب المرتجع':'Return reason'}/></label></div><div className="tableWrap"><table><thead><tr><th>{ar?'المنتج':'Product'}</th><th>{ar?'الكمية الأصلية':'Original Qty'}</th><th>{ar?'سعر الوحدة':'Unit Price'}</th><th>{ar?'كمية المرتجع':'Return Qty'}</th></tr></thead><tbody>{lines.map(l=><tr key={l.id}><td>{l.item.code} — {l.item.name}</td><td>{l.quantity}</td><td>{l.unitPrice}</td><td><input className="cellInput" inputMode="decimal" value={qty[l.id]??''} onChange={e=>setQty(v=>({...v,[l.id]:e.target.value}))}/></td></tr>)}</tbody></table></div>{message&&<div className="formMessage">{message}</div>}<div className="formActions"><button className="ghost" onClick={()=>router.back()}>{ar?'إلغاء':'Cancel'}</button><button className="primary" disabled={busy} onClick={submit}>{busy?(ar?'جاري الترحيل...':'Posting...'):(ar?'ترحيل المرتجع':'Post Return')}</button></div></section></>}
