'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, getCompanyId, idempotencyHeaders } from '@/lib/api';

type Customer={id:string;name:string};type Supplier={id:string;name:string};type Journal={id:string;journalNumber:string;sourceType:string;transactionDate:string;status:string;lines:Array<{baseDebit:string;baseCredit:string}>};
type Aging={invoiceId?:string;invoiceNumber?:string;billId?:string;billNumber?:string;customerId?:string;supplierId?:string;customer?:string;supplier?:string;outstanding:string};
export default function Page(){return <ErpShell><Payments/></ErpShell>}
function Payments(){const {locale}=useLocale();const ar=locale==='ar';const companyId=getCompanyId();const [mode,setMode]=useState<'customer'|'supplier'>('customer');const [customers,setCustomers]=useState<Customer[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[journals,setJournals]=useState<Journal[]>([]),[aging,setAging]=useState<Aging[]>([]);const [partyId,setPartyId]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[reference,setReference]=useState(''),[documentId,setDocumentId]=useState('');const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const load=async()=>{try{const [c,s,j,a]=await Promise.all([apiGet<Customer[]>(`/erp/customers/${companyId}`),apiGet<Supplier[]>(`/erp/suppliers/${companyId}`),apiGet<Journal[]>(`/erp/journals/${companyId}`),apiGet<Aging[]>(mode==='customer'?`/reports/customer-aging/${companyId}`:`/reports/supplier-aging/${companyId}`)]);setCustomers(c);setSuppliers(s);setJournals(j);setAging(a);setPartyId((mode==='customer'?c[0]?.id:s[0]?.id)??'')}catch(e){setMessage(e instanceof Error?e.message:String(e))}};
  useEffect(()=>{load()},[companyId,mode]);useEffect(()=>{setPartyId((mode==='customer'?customers[0]?.id:suppliers[0]?.id)??'');setDocumentId('')},[mode,customers,suppliers]);const history=useMemo(()=>journals.filter(j=>j.sourceType==='CustomerPayment'||j.sourceType==='SupplierPayment'),[journals]);const partyDocs=aging.filter(a=>(mode==='customer'?a.customerId:a.supplierId)===partyId);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!partyId||!amount)return;setBusy(true);setMessage('');try{const allocation=documentId?(mode==='customer'?{allocations:[{invoiceId:documentId,amount}]}:{allocations:[{billId:documentId,amount}]}):{};if(mode==='customer')await apiPost('/payments/customer-receipt',{companyId,customerId:partyId,amount,date:`${date}T12:00:00Z`,currencyCode:'SAR',exchangeRate:'1',reference,...allocation},idempotencyHeaders());else await apiPost('/payments/supplier-payment',{companyId,supplierId:partyId,amount,date:`${date}T12:00:00Z`,currencyCode:'SAR',exchangeRate:'1',reference,...allocation},idempotencyHeaders());setAmount('');setReference('');setDocumentId('');setMessage(ar?'تم ترحيل الحركة':'Transaction posted');await load()}catch(err){setMessage(err instanceof Error?err.message:String(err))}finally{setBusy(false)}};
  return <><div className="heading"><div><h1>{ar?'الصندوق والبنوك':'Cash & Banks'}</h1><p>{ar?'سندات القبض والصرف مع تخصيص الدفعات للفواتير':'Receipts and payments with invoice allocations'}</p></div></div><section className="gridTwo"><form className="card" onSubmit={submit}><div className="cardTitle"><h2>{mode==='customer'?(ar?'سند قبض عميل':'Customer Receipt'):(ar?'دفعة مورد':'Supplier Payment')}</h2></div><div className="segmented"><button type="button" className={mode==='customer'?'primary':'ghost'} onClick={()=>setMode('customer')}>{ar?'قبض':'Receipt'}</button><button type="button" className={mode==='supplier'?'primary':'ghost'} onClick={()=>setMode('supplier')}>{ar?'صرف':'Payment'}</button></div><label>{mode==='customer'?(ar?'العميل':'Customer'):(ar?'المورد':'Supplier')}<select value={partyId} onChange={e=>{setPartyId(e.target.value);setDocumentId('')}}>{(mode==='customer'?customers:suppliers).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{ar?'تخصيص لفاتورة':'Allocate to document'}<select value={documentId} onChange={e=>{setDocumentId(e.target.value);const d=partyDocs.find(x=>(x.invoiceId??x.billId)===e.target.value);if(d)setAmount(d.outstanding)}}><option value="">{ar?'بدون تخصيص':'Unallocated'}</option>{partyDocs.map(d=><option key={d.invoiceId??d.billId} value={d.invoiceId??d.billId}>{d.invoiceNumber??d.billNumber} — {Number(d.outstanding).toLocaleString()} SAR</option>)}</select></label><label>{ar?'المبلغ':'Amount'}<input required value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/></label><label>{ar?'التاريخ':'Date'}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{ar?'المرجع':'Reference'}<input value={reference} onChange={e=>setReference(e.target.value)} placeholder={ar?'اختياري':'Optional'}/></label>{message&&<div className="formMessage">{message}</div>}<button className="primary" disabled={busy}>{busy?(ar?'جاري الترحيل...':'Posting...'):(ar?'حفظ وترحيل':'Save & Post')}</button></form><div className="card"><div className="cardTitle"><h2>{ar?'آخر الحركات':'Recent Transactions'}</h2></div><div className="tableWrap"><table><thead><tr><th>{ar?'رقم القيد':'Journal #'}</th><th>{ar?'النوع':'Type'}</th><th>{ar?'التاريخ':'Date'}</th><th>{ar?'المبلغ':'Amount'}</th></tr></thead><tbody>{history.slice(0,10).map(j=>{const total=j.lines.reduce((a,l)=>a+Number(l.baseDebit),0);return <tr key={j.id}><td>{j.journalNumber}</td><td>{j.sourceType}</td><td>{j.transactionDate.slice(0,10)}</td><td>{total.toFixed(2)}</td></tr>})}</tbody></table></div></div></section></>}
