'use client';
import { isPreviewMode } from '@/lib/preview-api';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Plus, Search, Undo2 } from 'lucide-react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, getCompanyId } from '@/lib/api';

type Line={baseDebit:string;baseCredit:string};
type Journal={id:string;journalNumber:string;sourceType:string;transactionDate:string;status:string;lines:Line[]};
export default function Page(){return <ErpShell><Journals/></ErpShell>}
function Journals(){const {locale}=useLocale();const ar=locale==='ar';const companyId=getCompanyId();const [rows,setRows]=useState<Journal[]>([]),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState('');const load=()=>apiGet<Journal[]>(`/erp/journals/${companyId}`).then(setRows).catch(e=>setError(e instanceof Error?e.message:String(e)));useEffect(()=>{load()},[companyId]);const filtered=useMemo(()=>rows.filter(r=>`${r.journalNumber} ${r.sourceType}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);const reverse=async(j:Journal)=>{if(!confirm(ar?`عكس القيد ${j.journalNumber}؟`:`Reverse journal ${j.journalNumber}?`))return;setBusy(j.id);setError('');try{await apiPost('/accounting/journals/reverse',{companyId,journalId:j.id,reversalDate:new Date().toISOString(),reason:ar?'تصحيح محاسبي':'Accounting correction'});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};return <><div className="heading"><div><h1>{ar?'القيود اليومية':'Journal Entries'}</h1><p>{ar?'قيود محاسبية مزدوجة مع سجل مراجعة وعكس آمن':'Double-entry journals with audit trail and safe reversal'}</p></div><Link className="primary" href="/journals/new"><Plus size={17}/>{ar?'قيد جديد':'New Journal'}</Link></div><section className="card"><div className="moduleToolbar"><div className="inlineSearch"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث في القيود...':'Search journals...'}/></div></div>{error&&<div className="formMessage">{error}</div>}<div className="tableWrap"><table><thead><tr><th>{ar?'رقم القيد':'Journal #'}</th><th>{ar?'المصدر':'Source'}</th><th>{ar?'التاريخ':'Date'}</th><th>{ar?'مدين':'Debit'}</th><th>{ar?'دائن':'Credit'}</th><th>{ar?'الحالة':'Status'}</th><th>{ar?'إجراء':'Action'}</th></tr></thead><tbody>{filtered.map(j=>{const debit=j.lines.reduce((a,l)=>a+Number(l.baseDebit),0),credit=j.lines.reduce((a,l)=>a+Number(l.baseCredit),0);return <tr key={j.id}><td>{j.journalNumber}</td><td>{j.sourceType}</td><td>{j.transactionDate.slice(0,10)}</td><td>{debit.toFixed(2)}</td><td>{credit.toFixed(2)}</td><td><span className={`status ${j.status==='Posted'?'paid':j.status==='Reversed'?'overdue':'partial'}`}>{ar?translate(j.status):j.status}</span></td><td>{j.status==='Posted'&&<button className="ghost" disabled={busy===j.id||(isPreviewMode()&&j.sourceType!=='Manual')} title={isPreviewMode()&&j.sourceType!=='Manual'?(ar?'عكس قيود المستندات يتطلب نسخة الخادم':'Document reversal requires the server edition'):undefined} onClick={()=>reverse(j)}><Undo2 size={15}/>{ar?'عكس':'Reverse'}</button>}</td></tr>})}</tbody></table></div></section></>}
function translate(s:string){return s==='Posted'?'مرحّل':s==='Reversed'?'معكوس':s==='Draft'?'مسودة':s}
