'use client';
import { useEffect, useState } from 'react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, getCompanyId } from '@/lib/api';

type Company={id:string;name:string;taxNumber?:string|null;baseCurrencyCode:string};
type FiscalYear={id:string;name:string;startDate:string;endDate:string;status:string};
export default function Page(){return <ErpShell><Body/></ErpShell>}
function Body(){const {locale}=useLocale();const ar=locale==='ar';const companyId=getCompanyId();const [company,setCompany]=useState<Company>({id:companyId,name:'',taxNumber:'',baseCurrencyCode:'SAR'});const [years,setYears]=useState<FiscalYear[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{Promise.all([apiGet<Company>(`/admin/company/${companyId}`),apiGet<FiscalYear[]>(`/admin/fiscal-years/${companyId}`)]).then(([c,y])=>{if(c)setCompany(c);setYears(y)}).catch(e=>setMessage(e instanceof Error?e.message:String(e)))},[companyId]);const save=async()=>{setBusy(true);setMessage('');try{const saved=await apiPost<Company>(`/admin/company/${companyId}`,{name:company.name,taxNumber:company.taxNumber||undefined,baseCurrencyCode:company.baseCurrencyCode});setCompany(saved);setMessage(ar?'تم حفظ الإعدادات':'Settings saved')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};return <><div className="heading"><div><h1>{ar?'الإعدادات':'Settings'}</h1><p>{ar?'إعدادات الشركة والضرائب والفترات والترقيم':'Company, tax, periods and numbering settings'}</p></div><button className="primary" disabled={busy} onClick={save}>{busy?(ar?'جاري الحفظ...':'Saving...'):(ar?'حفظ التغييرات':'Save Changes')}</button></div>{message&&<div className="card formMessage">{message}</div>}<section className="settingsGrid"><div className="card"><h3>{ar?'معلومات الشركة':'Company Profile'}</h3><label>{ar?'اسم الشركة':'Company name'}<input value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/></label><label>{ar?'الرقم الضريبي':'Tax number'}<input value={company.taxNumber??''} onChange={e=>setCompany({...company,taxNumber:e.target.value})}/></label><label>{ar?'العملة الأساسية':'Base currency'}<select value={company.baseCurrencyCode} onChange={e=>setCompany({...company,baseCurrencyCode:e.target.value})}><option>SAR</option><option>USD</option></select></label></div><div className="card"><h3>{ar?'السنة المالية':'Fiscal Year'}</h3>{years.length?years.map(y=><div className="settingLine" key={y.id}><b>{y.name}</b><span>{y.startDate.slice(0,10)} — {y.endDate.slice(0,10)}</span><span className={`status ${y.status==='Closed'?'overdue':'paid'}`}>{y.status}</span></div>):<p>{ar?'لا توجد سنوات مالية':'No fiscal years'}</p>}<label>{ar?'طريقة تكلفة المخزون':'Inventory costing'}<select defaultValue="FIFO"><option>FIFO</option></select></label><label>{ar?'دقة المبالغ':'Amount precision'}<select defaultValue="4"><option>4</option></select></label></div><div className="card"><h3>{ar?'قواعد النظام':'System Rules'}</h3><p>{ar?'القيود المرحلة غير قابلة للتعديل ويجب عكسها بقيد عكسي.':'Posted journals are immutable and must be corrected through a reversal.'}</p><p>{ar?'تكلفة المخزون تطبق FIFO حسب المستودع.':'Inventory costing uses warehouse-scoped FIFO.'}</p><p>{ar?'التقارير الرسمية تستخدم العملة الأساسية.':'Official reports use base currency amounts.'}</p></div></section></>}
