'use client';
import { useEffect,useState,type FormEvent } from 'react';
import { BrainCircuit,Send,ShieldCheck } from 'lucide-react';
import { apiPost,getCompanyId,getSession } from '@/lib/api';
import { useLocale } from '@/components/erp-shell';

type Answer={answer:string;intent:string;facts:Record<string,unknown>;requestId:string;disclaimer:string};

export default function FinancialAiPage(){
 const {locale}=useLocale(),ar=locale==='ar',[question,setQuestion]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[allowed,setAllowed]=useState(false);
 useEffect(()=>{const s=getSession(),companyId=getCompanyId(),m=s?.memberships.find(x=>x.companyId===companyId);setAllowed(!!m&&['Owner','FinancialManager'].includes(m.role))},[]);
 const examples=ar?['ما صافي الدخل هذا الشهر؟','قارن الربحية بالشهر السابق','كم إجمالي الذمم المدينة على العملاء؟','كم الذمم الدائنة للموردين؟','ما إجمالي أرصدة البنوك؟']:['What is net income this month?','Compare profitability with last month','What are total customer receivables?','What are total supplier payables?','What are total bank balances?'];
 async function submit(e:FormEvent){e.preventDefault();if(!question.trim()||loading)return;setLoading(true);setError('');setAnswer(null);try{setAnswer(await apiPost<Answer>(`/companies/${getCompanyId()}/financial-ai/ask`,{question:question.trim(),language:locale}))}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setLoading(false)}}
 if(!allowed)return <section className="page"><div className="card"><ShieldCheck size={28}/><h1>{ar?'المساعد المالي الذكي':'Financial Intelligence'}</h1><p>{ar?'هذه المساحة متاحة فقط لصاحب الشركة والمدير المالي.':'This workspace is restricted to the company owner and financial manager.'}</p></div></section>;
 return <section className="page"><div className="pageHeader"><div><h1 style={{display:'flex',gap:10,alignItems:'center'}}><BrainCircuit size={28}/>{ar?'المساعد المالي الذكي':'Financial Intelligence'}</h1><p>{ar?'تحليل مالي إداري مبني على القيود والبيانات المرحلة — للقراءة فقط.':'Read-only management analysis grounded in posted accounting data.'}</p></div></div><div className="card"><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{examples.map(x=><button key={x} type="button" className="secondary" onClick={()=>setQuestion(x)}>{x}</button>)}</div><form onSubmit={submit}><label htmlFor="financial-question"><b>{ar?'اسأل عن الوضع المالي للشركة':'Ask about company financials'}</b></label><textarea id="financial-question" value={question} onChange={e=>setQuestion(e.target.value.slice(0,500))} rows={4} maxLength={500} placeholder={ar?'مثال: قارن الربحية بالشهر السابق':'Example: Compare profitability with last month'} style={{width:'100%',marginTop:8}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:10}}><small>{question.length}/500</small><button type="submit" disabled={loading||!question.trim()}><Send size={16}/>{loading?(ar?'جاري التحليل...':'Analyzing...'):(ar?'تحليل':'Analyze')}</button></div></form>{error&&<div className="formMessage" role="alert" style={{marginTop:16}}>{error}</div>}{answer&&<article style={{marginTop:20}}><h2>{ar?'النتيجة':'Result'}</h2><p style={{fontSize:'1.08rem',lineHeight:1.9}}>{answer.answer}</p><details><summary>{ar?'عرض الحقائق المالية المستخدمة':'Show financial facts used'}</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(answer.facts,null,2)}</pre></details><p><small>{answer.disclaimer} · Request ID: {answer.requestId}</small></p></article>}</div></section>
}
