'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, DEMO_COMPANY_ID } from '@/lib/api';

type Supplier={id:string;name:string}; type Warehouse={id:string;name:string}; type Item={id:string;code:string;name:string}; type TaxRate={id:string;name:string;rate:string};
type Line={itemId:string;quantity:string;unitCost:string;taxRateId?:string};

export default function Page(){return <ErpShell><PurchaseForm/></ErpShell>}
function PurchaseForm(){
  const {locale}=useLocale(); const ar=locale==='ar'; const router=useRouter();
  const [suppliers,setSuppliers]=useState<Supplier[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[items,setItems]=useState<Item[]>([]),[taxes,setTaxes]=useState<TaxRate[]>([]);
  const [supplierId,setSupplierId]=useState(''),[warehouseId,setWarehouseId]=useState(''),[date,setDate]=useState('2026-09-11'),[currency,setCurrency]=useState('SAR');
  const [lines,setLines]=useState<Line[]>([{itemId:'',quantity:'1',unitCost:'0'}]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{Promise.all([apiGet<Supplier[]>(`/erp/suppliers/${DEMO_COMPANY_ID}`),apiGet<Warehouse[]>(`/erp/warehouses/${DEMO_COMPANY_ID}`),apiGet<Item[]>(`/erp/items/${DEMO_COMPANY_ID}`),apiGet<TaxRate[]>(`/erp/tax-rates/${DEMO_COMPANY_ID}`)]).then(([s,w,i,t])=>{setSuppliers(s);setWarehouses(w);setItems(i);setTaxes(t);setSupplierId(s[0]?.id??'');setWarehouseId(w[0]?.id??'');setLines([{itemId:i[0]?.id??'',quantity:'1',unitCost:'0',taxRateId:t[0]?.id}])}).catch(()=>setMessage(ar?'تعذر الاتصال بالخادم':'Could not connect to the API'))},[ar]);
  const totals=useMemo(()=>lines.reduce((a,l)=>{const q=Number(l.quantity)||0,c=Number(l.unitCost)||0;const tax=taxes.find(t=>t.id===l.taxRateId);const net=q*c;return {net:a.net+net,tax:a.tax+net*Number(tax?.rate??0)}},{net:0,tax:0}),[lines,taxes]);
  const update=(index:number,key:keyof Line,value:string)=>setLines(v=>v.map((l,i)=>i===index?{...l,[key]:value}:l));
  const submit=async()=>{if(!supplierId||!warehouseId||lines.some(l=>!l.itemId)){setMessage(ar?'أكمل بيانات الفاتورة':'Complete the bill details');return}setBusy(true);setMessage('');try{await apiPost('/purchases/bill',{companyId:DEMO_COMPANY_ID,supplierId,warehouseId,billDate:`${date}T12:00:00Z`,currencyCode:currency,exchangeRate:'1',lines});setMessage(ar?'تم ترحيل فاتورة الشراء':'Purchase bill posted');setTimeout(()=>router.push('/purchases'),700)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  return <><div className="heading"><div><h1>{ar?'فاتورة شراء جديدة':'New Purchase Bill'}</h1><p>{ar?'استلام المخزون وتسجيل الالتزام والضريبة في عملية واحدة':'Receive inventory and post payable and tax in one transaction'}</p></div></div><section className="card invoiceForm"><div className="formGrid"><label>{ar?'المورد':'Supplier'}<select value={supplierId} onChange={e=>setSupplierId(e.target.value)}>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>{ar?'التاريخ':'Date'}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{ar?'العملة':'Currency'}<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>SAR</option><option>USD</option></select></label><label>{ar?'المستودع':'Warehouse'}<select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></div><div className="tableWrap"><table><thead><tr><th>{ar?'المنتج':'Product'}</th><th>{ar?'الكمية':'Qty'}</th><th>{ar?'تكلفة الوحدة':'Unit Cost'}</th><th>{ar?'الضريبة':'Tax'}</th><th>{ar?'الإجمالي':'Total'}</th><th></th></tr></thead><tbody>{lines.map((line,index)=>{const tax=taxes.find(t=>t.id===line.taxRateId);const total=(Number(line.quantity)||0)*(Number(line.unitCost)||0)*(1+Number(tax?.rate??0));return <tr key={index}><td><select value={line.itemId} onChange={e=>update(index,'itemId',e.target.value)}>{items.map(i=><option key={i.id} value={i.id}>{i.code} — {i.name}</option>)}</select></td><td><input className="cellInput" value={line.quantity} onChange={e=>update(index,'quantity',e.target.value)}/></td><td><input className="cellInput" value={line.unitCost} onChange={e=>update(index,'unitCost',e.target.value)}/></td><td><select value={line.taxRateId??''} onChange={e=>update(index,'taxRateId',e.target.value)}><option value="">0%</option>{taxes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></td><td>{total.toFixed(2)}</td><td><button className="ghost" onClick={()=>setLines(v=>v.filter((_,i)=>i!==index))}>×</button></td></tr>})}</tbody></table></div><button className="ghost" onClick={()=>setLines(v=>[...v,{itemId:items[0]?.id??'',quantity:'1',unitCost:'0',taxRateId:taxes[0]?.id}])}>+ {ar?'إضافة منتج':'Add Product'}</button><div className="invoiceSummary"><div><span>{ar?'المجموع الفرعي':'Subtotal'}</span><b>{totals.net.toFixed(2)} {currency}</b></div><div><span>{ar?'الضريبة':'Tax'}</span><b>{totals.tax.toFixed(2)} {currency}</b></div><div className="grand"><span>{ar?'الإجمالي الكلي':'Grand Total'}</span><b>{(totals.net+totals.tax).toFixed(2)} {currency}</b></div></div>{message&&<div className="formMessage">{message}</div>}<div className="formActions"><button className="ghost" onClick={()=>router.back()}>{ar?'إلغاء':'Cancel'}</button><button className="primary" disabled={busy} onClick={submit}>{busy?(ar?'جاري الترحيل...':'Posting...'):(ar?'حفظ وترحيل':'Save & Post')}</button></div></section></>}
