import { Body,Controller,Get,Param,Post,Query,UseGuards } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from './prisma.service';
import { PostingConfigService } from './posting-config.service';
import { JwtAuthGuard } from './jwt-auth.guard';
import { RolesGuard } from './roles.guard';
import { PermissionGuard,RequirePermission } from './permission.guard';
@UseGuards(JwtAuthGuard,RolesGuard,PermissionGuard)@Controller('erp')
export class ErpController{
 constructor(private readonly prisma:PrismaService,private readonly postingConfig:PostingConfigService){}
 @RequirePermission('dashboard.read')@Get('company/:companyId') company(@Param('companyId') companyId:string){return this.prisma.company.findUnique({where:{id:companyId},select:{id:true,name:true,taxNumber:true,baseCurrencyCode:true}})}
 @RequirePermission('accounting.read')@Get('exchange-rate/:companyId/:currencyCode') async exchangeRate(@Param('companyId') companyId:string,@Param('currencyCode') currencyCode:string,@Query('date') date?:string){const company=await this.prisma.company.findUnique({where:{id:companyId}});if(!company)return null;if(currencyCode===company.baseCurrencyCode)return {currencyCode,rate:'1',rateDate:date??new Date().toISOString().slice(0,10)};return this.prisma.exchangeRate.findFirst({where:{companyId,currencyCode,rateDate:{lte:date?new Date(`${date}T23:59:59.999Z`):new Date()}},orderBy:{rateDate:'desc'}})}
 @RequirePermission('dashboard.read')@Get('dashboard/:companyId') async dashboard(@Param('companyId') companyId:string){const config=await this.postingConfig.get(this.prisma as unknown as Prisma.TransactionClient,companyId).catch(()=>null);let sales=new Prisma.Decimal(0),purchases=new Prisma.Decimal(0);if(config){const [s,p]=await Promise.all([this.prisma.journalLine.findMany({where:{accountId:config.receivableAccountId,journal:{companyId,sourceType:{in:['SalesInvoice','CreditNote']},status:{in:['Posted','Reversed']}}},select:{baseDebit:true,baseCredit:true}}),this.prisma.journalLine.findMany({where:{accountId:config.payableAccountId,journal:{companyId,sourceType:'PurchaseBill',status:{in:['Posted','Reversed']}}},select:{baseDebit:true,baseCredit:true}})]);for(const l of s)sales=sales.add(l.baseDebit).sub(l.baseCredit);for(const l of p)purchases=purchases.add(l.baseCredit).sub(l.baseDebit)}const [customers,suppliers,items,journals,company]=await Promise.all([this.prisma.customer.count({where:{companyId,isActive:true}}),this.prisma.supplier.count({where:{companyId,isActive:true}}),this.prisma.item.count({where:{companyId,isActive:true}}),this.prisma.journal.count({where:{companyId,status:{in:['Posted','Reversed']}}}),this.prisma.company.findUnique({where:{id:companyId},select:{baseCurrencyCode:true}})]);return {sales:sales.toString(),purchases:purchases.toString(),customers,suppliers,items,journals,baseCurrencyCode:company?.baseCurrencyCode??''}}
 @RequirePermission('customers.read')@Get('customers/:companyId') customers(@Param('companyId') companyId:string){return this.prisma.customer.findMany({where:{companyId},orderBy:{createdAt:'desc'}})}
 @RequirePermission('customers.write')@Post('customers/:companyId') createCustomer(@Param('companyId') companyId:string,@Body() body:{code:string;name:string;email?:string;phone?:string;taxNumber?:string}){return this.prisma.customer.create({data:{companyId,...body}})}
 @RequirePermission('suppliers.read')@Get('suppliers/:companyId') suppliers(@Param('companyId') companyId:string){return this.prisma.supplier.findMany({where:{companyId},orderBy:{createdAt:'desc'}})}
 @RequirePermission('suppliers.write')@Post('suppliers/:companyId') createSupplier(@Param('companyId') companyId:string,@Body() body:{code:string;name:string;email?:string;phone?:string;taxNumber?:string}){return this.prisma.supplier.create({data:{companyId,...body}})}
 @RequirePermission('inventory.read')@Get('items/:companyId') items(@Param('companyId') companyId:string){return this.prisma.item.findMany({where:{companyId},include:{lots:true},orderBy:{code:'asc'}})}
 @RequirePermission('inventory.read')@Get('warehouses/:companyId') warehouses(@Param('companyId') companyId:string){return this.prisma.warehouse.findMany({where:{companyId,isActive:true},orderBy:{code:'asc'}})}
 @RequirePermission('accounting.read')@Get('tax-rates/:companyId') taxRates(@Param('companyId') companyId:string){return this.prisma.taxRate.findMany({where:{companyId},orderBy:[{code:'asc'},{effectiveFrom:'desc'}]})}
 @RequirePermission('accounting.read')@Get('accounts/:companyId') accounts(@Param('companyId') companyId:string){return this.prisma.account.findMany({where:{companyId},orderBy:{code:'asc'}})}
 @RequirePermission('sales.read')@Get('sales/:companyId') async sales(@Param('companyId') companyId:string){const docs=await this.prisma.salesInvoice.findMany({where:{companyId},include:{customer:true,lines:{include:{item:true}}},orderBy:{invoiceDate:'desc'}}),journals=await this.prisma.journal.findMany({where:{companyId,sourceType:'SalesInvoice',sourceId:{in:docs.map(d=>d.id)}},orderBy:{createdAt:'asc'},select:{sourceId:true,currencyCode:true,exchangeRate:true,status:true}}),map=new Map<string,{currencyCode:string;exchangeRate:string;status:string}>();for(const j of journals)if(j.sourceId&&!map.has(j.sourceId))map.set(j.sourceId,{currencyCode:j.currencyCode,exchangeRate:j.exchangeRate.toString(),status:j.status});return docs.map(d=>({...d,...(map.get(d.id)??{})}))}
 @RequirePermission('purchases.read')@Get('purchases/:companyId') async purchases(@Param('companyId') companyId:string){const docs=await this.prisma.purchaseBill.findMany({where:{companyId},include:{supplier:true,lines:{include:{item:true}}},orderBy:{billDate:'desc'}}),journals=await this.prisma.journal.findMany({where:{companyId,sourceType:'PurchaseBill',sourceId:{in:docs.map(d=>d.id)}},orderBy:{createdAt:'asc'},select:{sourceId:true,currencyCode:true,exchangeRate:true,status:true}}),map=new Map<string,{currencyCode:string;exchangeRate:string;status:string}>();for(const j of journals)if(j.sourceId&&!map.has(j.sourceId))map.set(j.sourceId,{currencyCode:j.currencyCode,exchangeRate:j.exchangeRate.toString(),status:j.status});return docs.map(d=>({...d,...(map.get(d.id)??{})}))}
 @RequirePermission('accounting.read')@Get('journals/:companyId') journals(@Param('companyId') companyId:string,@Query('take') take='100'){return this.prisma.journal.findMany({where:{companyId},include:{lines:{include:{account:true}}},orderBy:{transactionDate:'desc'},take:Math.min(Number(take)||100,500)})}
 @RequirePermission('reports.read')@Get('trial-balance/:companyId') async trialBalance(@Param('companyId') companyId:string,@Query('from') from?:string,@Query('to') to?:string){const rows=await this.prisma.journalLine.groupBy({by:['accountId'],where:{journal:{companyId,status:{in:['Posted','Reversed']},transactionDate:{gte:from?new Date(from):undefined,lte:to?new Date(to):undefined}}},_sum:{baseDebit:true,baseCredit:true}}),accounts=await this.prisma.account.findMany({where:{id:{in:rows.map(r=>r.accountId)}}}),map=new Map(accounts.map(a=>[a.id,a]));return rows.map(r=>({accountCode:map.get(r.accountId)?.code,accountName:map.get(r.accountId)?.name,debit:r._sum.baseDebit?.toString()??'0',credit:r._sum.baseCredit?.toString()??'0'}))}
 @RequirePermission('reports.read')@Get('profit-loss/:companyId') async profitLoss(@Param('companyId') companyId:string,@Query('from') from?:string,@Query('to') to?:string){const lines=await this.prisma.journalLine.findMany({where:{journal:{companyId,status:{in:['Posted','Reversed']},sourceType:{not:'YearEndClosing'},transactionDate:{gte:from?new Date(from):undefined,lte:to?new Date(to):undefined}},account:{type:{in:['Revenue','Expense']}}},include:{account:true}});let revenue=new Prisma.Decimal(0),expense=new Prisma.Decimal(0);for(const l of lines){if(l.account.type==='Revenue')revenue=revenue.add(l.baseCredit).sub(l.baseDebit);else expense=expense.add(l.baseDebit).sub(l.baseCredit)}return {revenue:revenue.toString(),expense:expense.toString(),netProfit:revenue.sub(expense).toString()}}
 @RequirePermission('reports.read')@Get('balance-sheet/:companyId') async balanceSheet(@Param('companyId') companyId:string,@Query('asOf') asOf?:string){const target=asOf?new Date(asOf):new Date(),lines=await this.prisma.journalLine.findMany({where:{journal:{companyId,status:{in:['Posted','Reversed']},transactionDate:{lte:target}},account:{type:{in:['Asset','Liability','Equity']}}},include:{account:true}}),balances=new Map<string,{code:string;name:string;type:string;balance:Prisma.Decimal}>();for(const l of lines){const current=balances.get(l.accountId)??{code:l.account.code,name:l.account.name,type:l.account.type,balance:new Prisma.Decimal(0)},movement=l.account.type==='Asset'?l.baseDebit.sub(l.baseCredit):l.baseCredit.sub(l.baseDebit);current.balance=current.balance.add(movement);balances.set(l.accountId,current)}const year=await this.prisma.fiscalYear.findFirst({where:{companyId,startDate:{lte:target},endDate:{gte:target}},orderBy:{startDate:'desc'}});if(year&&year.status!=='Closed'){const nominal=await this.prisma.journalLine.findMany({where:{journal:{companyId,status:{in:['Posted','Reversed']},sourceType:{not:'YearEndClosing'},transactionDate:{gte:year.startDate,lte:target}},account:{type:{in:['Revenue','Expense']}}},include:{account:true}});let revenue=new Prisma.Decimal(0),expense=new Prisma.Decimal(0);for(const l of nominal){if(l.account.type==='Revenue')revenue=revenue.add(l.baseCredit).sub(l.baseDebit);else expense=expense.add(l.baseDebit).sub(l.baseCredit)}balances.set('__CURRENT_YEAR_EARNINGS__',{code:'',name:'Current Year Earnings',type:'Equity',balance:revenue.sub(expense)})}return [...balances.values()].map(x=>({...x,balance:x.balance.toString()}))}
 @RequirePermission('reports.read')@Get('inventory-valuation/:companyId') async inventoryValuation(@Param('companyId') companyId:string){const lots=await this.prisma.inventoryLot.findMany({where:{companyId,remainingQuantity:{gt:0}},include:{item:true,warehouse:true},orderBy:[{item:{code:'asc'}},{receivedDate:'asc'}]});return lots.map(l=>({itemCode:l.item.code,itemName:l.item.name,warehouse:l.warehouse.name,receivedDate:l.receivedDate.toISOString().slice(0,10),quantity:l.remainingQuantity.toString(),unitCost:l.unitCost.toString(),value:l.remainingQuantity.mul(l.unitCost).toDecimalPlaces(4).toString()}))}
 @RequirePermission('reports.read')@Get('account-activity/:companyId') accountActivity(@Param('companyId') companyId:string,@Query('accountId') accountId?:string,@Query('from') from?:string,@Query('to') to?:string){return this.prisma.journalLine.findMany({where:{accountId:accountId||undefined,journal:{companyId,status:{in:['Posted','Reversed']},transactionDate:{gte:from?new Date(from):undefined,lte:to?new Date(to):undefined}}},include:{account:true,journal:true},orderBy:{journal:{transactionDate:'asc'}},take:1000})}
}
