'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { Plus,Search } from 'lucide-react';
import { ErpShell,useLocale } from '@/components/erp-shell';
import { apiGet,getCompanyId } from '@/lib/api';
type Invoice={id:string;invoiceNumber:string;invoiceDate:string;grandTotal:string;status:string;currencyCode?:string;customer:{name:string}};
export default function Page(){return <ErpShell><SalesList/></ErpShell>}
function SalesList(){const {locale}=useLocale(),ar=locale==='ar',companyId=getCompanyId();const [rows,setRows]=useState<Invoice[]>([]),[q,setQ]=useState(''),[error,setError]=useState('');useEffect(()=>{apiGet<Invoice[]>(`/erp/sales/${companyId}`).then(setRows).catch(e=>setError(e instanceof Error?e.message:String(e)))},[companyId]);const filtered=rows.filter(r=>`${r.invoiceNumber} ${r.customer.name}`.toLowerCase().includes(q.toLowerCase()));return <><div className="heading"><div><h1>{ar?'الفواتير والمبيعات':'Invoices & Sales'}</h1><p>{ar?'إدارة فواتير العملاء والمبيعات والمرتجعات':'Manage customer invoices, sales and returns'}</p></div><div className="formActions"><Link className="ghost" href="/sales/credit-notes">{ar?'الإشعارات الدائنة':'Credit Notes'}</Link><Link className="primary" href="/sales/new"><Plus size={17}/>{ar?'فاتورة جديدة':'New Invoice'}</Link></div></div><section className="card"><div className="moduleToolbar"><div className="inlineSearch"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث في الفواتير...':'Search invoices...'}/></div></div>{error&&<div className="formMessage">{error}</div>}<div className="tableWrap"><table><thead><tr><th>{ar?'رقم الفاتورة':'Invoice #'}</th><th>{ar?'العميل':'Customer'}</th><th>{ar?'التاريخ':'Date'}</th><th>{ar?'الإجمالي':'Total'}</th><th>{ar?'الحالة':'Status'}</th><th></th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id}><td>{r.invoiceNumber}</td><td>{r.customer.name}</td><td>{r.invoiceDate.slice(0,10)}</td><td>{format(r.grandTotal)} {r.currencyCode??''}</td><td><span className={`status ${r.status==='Posted'?'paid':'partial'}`}>{ar?translate(r.status):r.status}</span></td><td>{r.status==='Posted'&&<Link className="ghost" href={`/sales/credit-notes/new?invoiceId=${r.id}`}>{ar?'مرتجع':'Return'}</Link>}</td></tr>):<tr><td colSpan={6}>{ar?'لا توجد فواتير بعد':'No invoices yet'}</td></tr>}</tbody></table></div></section></>}
function format(v:string){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n):v}function translate(s:string){return s==='Posted'?'مرحلة':s==='Draft'?'مسودة':s==='Cancelled'?'ملغاة':s}
