'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { ErpShell, useLocale } from '@/components/erp-shell';
import { apiGet, apiPost, getCompanyId } from '@/lib/api';

type Membership={id:string;role:string;dataScope?:string|null;user:{id:string;email:string;fullName:string}};
export default function Page(){return <ErpShell><Users/></ErpShell>}
function Users(){const {locale}=useLocale();const ar=locale==='ar';const companyId=getCompanyId();const [rows,setRows]=useState<Membership[]>([]),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const [form,setForm]=useState({email:'',fullName:'',role:'Accountant',dataScope:'all'});const load=()=>apiGet<Membership[]>(`/admin/users/${companyId}`).then(setRows).catch(e=>setError(e instanceof Error?e.message:String(e)));useEffect(()=>{load()},[companyId]);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await apiPost(`/admin/users/${companyId}`,form);setShow(false);setForm({email:'',fullName:'',role:'Accountant',dataScope:'all'});await load()}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}};return <><div className="heading"><div><h1>{ar?'المستخدمون والصلاحيات':'Users & Permissions'}</h1><p>{ar?'إدارة المستخدمين والأدوار ونطاق الوصول':'Manage users, roles and access scope'}</p></div><button className="primary" onClick={()=>setShow(true)}><Plus size={17}/>{ar?'مستخدم جديد':'New User'}</button></div>{show&&<section className="card quickForm"><div className="cardTitle"><h2>{ar?'إضافة مستخدم':'Add User'}</h2><button className="ghost" onClick={()=>setShow(false)}><X size={16}/></button></div><form className="formGrid" onSubmit={submit}><label>{ar?'الاسم':'Full Name'}<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>{ar?'البريد الإلكتروني':'Email'}<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>{ar?'الدور':'Role'}<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Admin</option><option>Owner</option><option>Accountant</option><option>Sales</option><option>Purchases</option><option>Employee</option></select></label><label>{ar?'نطاق البيانات':'Data Scope'}<select value={form.dataScope} onChange={e=>setForm({...form,dataScope:e.target.value})}><option value="all">All company</option><option value="finance">Finance</option><option value="sales">Sales</option><option value="purchases">Purchases</option><option value="read">Read only</option></select></label><div className="formActions"><button className="primary" disabled={busy}>{busy?(ar?'جاري الحفظ...':'Saving...'):(ar?'حفظ':'Save')}</button></div></form></section>}<section className="card">{error&&<div className="formMessage">{error}</div>}<div className="tableWrap"><table><thead><tr><th>{ar?'الاسم':'Name'}</th><th>{ar?'البريد الإلكتروني':'Email'}</th><th>{ar?'الدور':'Role'}</th><th>{ar?'نطاق البيانات':'Data Scope'}</th><th>{ar?'الحالة':'Status'}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.user.fullName}</td><td>{r.user.email}</td><td>{r.role}</td><td>{r.dataScope??'—'}</td><td><span className="status paid">{ar?'نشط':'Active'}</span></td></tr>)}</tbody></table></div></section></>}
