export type InfoSection = { ar: [string, string]; en: [string, string] };
export const platformInfo: Record<string, { ar: string; en: string; sections: InfoSection[] }> = {
  about: { ar: 'عن المنصة', en: 'About the platform', sections: [
    { ar: ['حسابات أوضح، إدارة أسهل', 'منصة محاسبية تجمع الفواتير والعملاء والموردين والمخزون والقيود والتقارير في مساحة واحدة، بواجهة عربية وإنجليزية. تصميم محمد العقلة.'], en: ['Clarity for everyday business', 'A bilingual workspace for invoices, customers, suppliers, inventory, journals and reports. Designed by Mohammed Al-Oqleh.'] },
    { ar: ['لمن صُممت؟', 'لأصحاب الأعمال وفرق الحسابات الذين يحتاجون إلى تنظيم عملياتهم وفهم حركة أعمالهم. النسخة العامة تتيح استكشاف تجربة الاستخدام ببيانات تجريبية.'], en: ['Who is it for?', 'Business owners and accounting teams who want to organise operations and understand business activity. The public edition lets you explore the experience with sample data.'] }
  ] },
  benefits: { ar: 'كيف تستفيد منها؟', en: 'How it helps', sections: [
    { ar: ['١. جهّز مساحة العمل', 'تعرّف على إعدادات الشركة والعملات والمستودعات والحسابات، ثم أضف بيانات تجريبية للعملاء والموردين والأصناف.'], en: ['1. Set up your workspace', 'Explore company settings, currencies, warehouses and accounts, then add sample customers, suppliers and items.'] },
    { ar: ['٢. تابع العمليات اليومية', 'استكشف المبيعات والمشتريات والمدفوعات وحركة المخزون من واجهات مترابطة. راجع المدخلات قبل تسجيل أي عملية.'], en: ['2. Follow daily operations', 'Explore sales, purchases, payments and inventory through connected screens. Review inputs before recording a transaction.'] },
    { ar: ['٣. اقرأ النتائج', 'استخدم ميزان المراجعة وتقارير المخزون والأرصدة لفهم النتائج. قارن التقارير بالمستندات الأصلية قبل اعتمادها في العمل الفعلي.'], en: ['3. Understand the results', 'Use trial balance, inventory and balance reports to understand activity. Reconcile reports with source documents before relying on them for real business.'] }
  ] },
  vision: { ar: 'رؤيتنا', en: 'Our vision', sections: [
    { ar: ['تجربة تتجاوز اللغة', 'نسعى إلى جعل إدارة الحسابات مفهومة وسهلة الوصول، مع دعم العربية والإنجليزية واتجاهي القراءة وتصميم يناسب الشاشات المختلفة.'], en: ['An experience across languages', 'Our goal is approachable accounting with Arabic and English, both reading directions and layouts for different screen sizes.'] },
    { ar: ['تطوير يستند إلى الاحتياج', 'نطوّر التجربة عبر الملاحظات العملية: وضوح البيانات وسهولة التنقل ودقة التحقق. هذه رؤية للتطوير، وليست ادعاءً بشهادات اعتماد أو امتثال لجميع البلدان.'], en: ['Development driven by real needs', 'We improve through practical feedback: clear data, simple navigation and sound validation. This is a development vision, not a claim of certification or compliance in every country.'] }
  ] },
  faq: { ar: 'الأسئلة الشائعة', en: 'Frequently asked questions', sections: [
    { ar: ['هل النسخة العامة نظام إنتاجي؟', 'نسخة GitHub Pages هي معاينة للتجربة وليست خدمة محاسبية سحابية لإدارة بيانات حساسة. استخدم بيانات وهمية عند التجربة.'], en: ['Is the public edition a production system?', 'The GitHub Pages edition is a preview, not a hosted accounting service for sensitive records. Use fictional data while exploring.'] },
    { ar: ['هل تنتقل بياناتي إلى جهاز آخر؟', 'بيانات المعاينة تُحفظ في متصفحك على هذا الجهاز ولا تتزامن تلقائيًا مع الأجهزة الأخرى. حذف بيانات الموقع أو استخدام متصفح مختلف قد يفقدك الوصول إليها.'], en: ['Does my data sync across devices?', 'Preview data is stored in this browser on this device, without automatic cross-device sync. Clearing site data or using another browser can make it unavailable.'] },
    { ar: ['هل تعمل جميع الشاشات مثل الخادم الفعلي؟', 'بعض الوظائف تمثيلية؛ المرتجعات في المعاينة لا تنفذ دورة الترحيل الكاملة، وإقفال السنة غير متاح فيها. لا تعتمد نتائج المعاينة لإقرارات ضريبية أو قوائم رسمية.'], en: ['Does every screen behave like the real backend?', 'Some functions are illustrative: preview returns do not implement the full posting cycle, and year-end closing is unavailable. Do not use preview results for tax filings or official statements.'] },
    { ar: ['كيف أبلغ عن مشكلة؟', 'راسلنا بوصف الخطوات ورسالة الخطأ ونوع الجهاز. أخفِ كلمات المرور وأسماء العملاء وأرقام الحسابات وأي بيانات مالية من الصور والمرفقات.'], en: ['How do I report an issue?', 'Send the steps, error message and device type. Remove passwords, customer names, account numbers and financial records from screenshots and attachments.'] }
  ] },
  privacy: { ar: 'الخصوصية والبيانات', en: 'Privacy & data', sections: [
    { ar: ['نطاق هذه الصفحة', 'تشرح هذه الصفحة سلوك النسخة العامة المنشورة على GitHub Pages. عند تشغيل نسخة متصلة بخادم، تُرسل عمليات الحسابات إلى ذلك الخادم وتخضع بياناتها لإدارة الجهة المشغلة. آخر تحديث: 12 سبتمبر 2026.'], en: ['Scope of this notice', 'This notice describes the public GitHub Pages edition. In a server-connected installation, accounting requests are sent to that server and its operator manages the records. Updated: 12 September 2026.'] },
    { ar: ['ما الذي يحفظه المتصفح؟', 'تستخدم المعاينة التخزين المحلي لحفظ بيانات العمليات التجريبية، والجلسة، والشركة المختارة، وتفضيل اللغة، وقيم تحقق كلمة مرور المعاينة عند تغييرها. لا تُشفّر سجلات المعاينة المخزنة محليًا؛ تجنب إدخال بيانات حقيقية أو حساسة.'], en: ['What is stored in your browser?', 'The preview uses local storage for sample transactions, the session, selected company, language preference and preview password verification values when changed. Locally stored preview records are not encrypted; avoid real or sensitive data.'] },
    { ar: ['الاستضافة والتواصل', 'لا تتضمن الواجهة الحالية أدوات إعلانات أو تحليلات مضافة من طرفنا. قد تجمع GitHub معلومات تقنية عن الزيارات، ومنها عنوان IP لأغراض الأمان. عند مراسلتنا بالبريد، تُعالج رسالتك ومعلومات تواصلك للرد عليها عبر مزود البريد.'], en: ['Hosting and contact', 'The current interface includes no advertising or analytics tools added by us. GitHub may collect technical visit information, including IP addresses for security. When you email us, your message and contact details are processed through the email provider to respond.'] },
    { ar: ['الاحتفاظ والتحكم', 'تبقى بيانات المعاينة في المتصفح حتى حذفها أو إزالتها بواسطة المتصفح. تسجيل الخروج يزيل الجلسة والشركة المختارة، ولا يحذف سجلات المعاينة. صفحة إدارة البيانات تشرح خياراتك؛ لا نمسح سجلاتك تلقائيًا عند فتح هذه الصفحات.'], en: ['Retention and control', 'Preview records remain until you or your browser remove them. Signing out removes the session and selected company, but not preview records. The data guide explains your options; opening these pages does not erase records.'] },
    { ar: ['طلبات الخصوصية', 'للاستفسار عن رسالة أرسلتها إلينا أو لطلب تصحيحها أو حذفها، تواصل عبر info.moqleh@yahoo.com. سجلات المعاينة المحلية لا تصل إلينا تلقائيًا ولا يمكننا حذفها عن بُعد.'], en: ['Privacy requests', 'For questions about a message you sent us, or to request its correction or deletion, contact info.moqleh@yahoo.com. Local preview records are not automatically sent to us and cannot be removed by us remotely.'] }
  ] },
  data: { ar: 'إدارة بياناتك', en: 'Manage your data', sections: [
    { ar: ['تسجيل الخروج', 'استخدم زر تسجيل الخروج داخل البرنامج لإنهاء الجلسة على هذا المتصفح. تبقى بيانات التجربة محفوظة؛ تسجيل الخروج ليس حذفًا للحساب أو للسجلات.'], en: ['Sign out', 'Use the sign-out button inside the app to end the session in this browser. Sample records remain; signing out does not delete an account or its records.'] },
    { ar: ['حذف بيانات المعاينة المحلية', 'بعد الاحتفاظ بما تحتاجه، افتح إعدادات المتصفح ← الخصوصية وبيانات المواقع ← ابحث عن moqleh.github.io ← امسح بيانات الموقع. هذا قد يحذف بيانات مواقع أخرى على نفس النطاق، ويعيد تفضيلات وكلمة مرور المعاينة المحلية؛ لا توجد استعادة تلقائية.'], en: ['Remove local preview data', 'After keeping what you need, open browser settings → privacy and site data → find moqleh.github.io → clear site data. This may also remove data for other sites on the same origin and reset local preview preferences and password settings. There is no automatic recovery.'] },
    { ar: ['عند استخدام خادم فعلي', 'مسح بيانات المتصفح لا يحذف البيانات من قاعدة بيانات الخادم. راجع مسؤول شركتك بخصوص الصلاحيات والاحتفاظ بالسجلات والنسخ الاحتياطية وطلبات الحذف.'], en: ['When using a real server', 'Clearing browser data does not delete server database records. Contact your company administrator about permissions, retention, backups and deletion requests.'] }
  ] },
  terms: { ar: 'شروط الاستخدام', en: 'Terms of use', sections: [
    { ar: ['استخدام مسؤول', 'استخدم المنصة في الأعمال المصرح لك بها فقط، وأدخل بيانات تملك حق استخدامها. لا تحاول الوصول إلى حسابات الغير أو تعطيل الخدمة أو إساءة استخدامها. آخر تحديث: 12 سبتمبر 2026.'], en: ['Responsible use', 'Use the platform only for authorised activities and data you have permission to use. Do not access other accounts, disrupt the service or misuse it. Updated: 12 September 2026.'] },
    { ar: ['حدود المعاينة', 'النسخة العامة مخصصة للتجربة. قد تتغير الوظائف، وقد تفقد البيانات المحلية عند مسح المتصفح. لا تتضمن المعاينة ضمان توافر مستمر أو خدمة نسخ احتياطي أو دعم بزمن استجابة محدد.'], en: ['Preview limitations', 'The public edition is for evaluation. Features may change, and browser data can be lost when cleared. The preview includes no guaranteed uptime, backup service or fixed support response time.'] },
    { ar: ['مراجعة النتائج', 'راجع المدخلات والتقارير قبل استخدامها. المنصة لا تقدم استشارة محاسبية أو ضريبية أو قانونية، ولا يغني استخدامها عن مراجعة مختص ومتطلبات الجهة المعنية في بلدك.'], en: ['Review the results', 'Check inputs and reports before use. The platform does not provide accounting, tax or legal advice and does not replace professional review or requirements applicable in your country.'] },
    { ar: ['التحديثات والاستفسارات', 'نوضح التغييرات في هذه الصفحة عند تحديث قواعد الاستخدام. للاستفسار عن الاستخدام أو الإبلاغ عن مشكلة، استخدم صفحة التواصل. لا تتضمن هذه الصفحة تنازلاً عن حقوق يقررها القانون الواجب التطبيق.'], en: ['Updates and questions', 'Changes to usage rules will be reflected here. Use the contact page for questions or issues. This page does not waive rights provided by applicable law.'] }
  ] },
  contact: { ar: 'تواصل معنا', en: 'Contact us', sections: [
    { ar: ['نستمع لملاحظاتك', 'للاقتراحات والدعم والاستفسارات المتعلقة بالخصوصية، تواصل مع محمد العقلة عبر البريد أو الهاتف أدناه. صف احتياجك بوضوح وسنراجع رسالتك.'], en: ['We welcome your feedback', 'For suggestions, support or privacy questions, contact Mohammed Al-Oqleh by email or phone below. Describe your request clearly so we can review it.'] },
    { ar: ['ماذا ترسل؟', 'اسم الصفحة ووصف المشكلة وخطوات تكرارها كافية للبدء. لا ترسل كلمات المرور أو رموز الدخول أو ملفات العملاء المحاسبية.'], en: ['What should you send?', 'Start with the page name, issue description and steps to reproduce it. Do not send passwords, sign-in codes or customer accounting files.'] }
  ] }
};
